// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.2
// source: log_platform.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectServerService_ListServers_FullMethodName  = "/logplatform.v1.ProjectServerService/ListServers"
	ProjectServerService_GetServer_FullMethodName    = "/logplatform.v1.ProjectServerService/GetServer"
	ProjectServerService_UpsertServer_FullMethodName = "/logplatform.v1.ProjectServerService/UpsertServer"
	ProjectServerService_DeleteServer_FullMethodName = "/logplatform.v1.ProjectServerService/DeleteServer"
)

// ProjectServerServiceClient is the client API for ProjectServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectServerServiceClient interface {
	ListServers(ctx context.Context, in *ListServersRequest, opts ...grpc.CallOption) (*ListServersResponse, error)
	GetServer(ctx context.Context, in *GetServerRequest, opts ...grpc.CallOption) (*ServerItem, error)
	UpsertServer(ctx context.Context, in *UpsertServerRequest, opts ...grpc.CallOption) (*ServerItem, error)
	DeleteServer(ctx context.Context, in *DeleteServerRequest, opts ...grpc.CallOption) (*DeleteServerResponse, error)
}

type projectServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServerServiceClient(cc grpc.ClientConnInterface) ProjectServerServiceClient {
	return &projectServerServiceClient{cc}
}

func (c *projectServerServiceClient) ListServers(ctx context.Context, in *ListServersRequest, opts ...grpc.CallOption) (*ListServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServersResponse)
	err := c.cc.Invoke(ctx, ProjectServerService_ListServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServerServiceClient) GetServer(ctx context.Context, in *GetServerRequest, opts ...grpc.CallOption) (*ServerItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerItem)
	err := c.cc.Invoke(ctx, ProjectServerService_GetServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServerServiceClient) UpsertServer(ctx context.Context, in *UpsertServerRequest, opts ...grpc.CallOption) (*ServerItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerItem)
	err := c.cc.Invoke(ctx, ProjectServerService_UpsertServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServerServiceClient) DeleteServer(ctx context.Context, in *DeleteServerRequest, opts ...grpc.CallOption) (*DeleteServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServerResponse)
	err := c.cc.Invoke(ctx, ProjectServerService_DeleteServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServerServiceServer is the server API for ProjectServerService service.
// All implementations must embed UnimplementedProjectServerServiceServer
// for forward compatibility.
type ProjectServerServiceServer interface {
	ListServers(context.Context, *ListServersRequest) (*ListServersResponse, error)
	GetServer(context.Context, *GetServerRequest) (*ServerItem, error)
	UpsertServer(context.Context, *UpsertServerRequest) (*ServerItem, error)
	DeleteServer(context.Context, *DeleteServerRequest) (*DeleteServerResponse, error)
	mustEmbedUnimplementedProjectServerServiceServer()
}

// UnimplementedProjectServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectServerServiceServer struct{}

func (UnimplementedProjectServerServiceServer) ListServers(context.Context, *ListServersRequest) (*ListServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServers not implemented")
}
func (UnimplementedProjectServerServiceServer) GetServer(context.Context, *GetServerRequest) (*ServerItem, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServer not implemented")
}
func (UnimplementedProjectServerServiceServer) UpsertServer(context.Context, *UpsertServerRequest) (*ServerItem, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertServer not implemented")
}
func (UnimplementedProjectServerServiceServer) DeleteServer(context.Context, *DeleteServerRequest) (*DeleteServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteServer not implemented")
}
func (UnimplementedProjectServerServiceServer) mustEmbedUnimplementedProjectServerServiceServer() {}
func (UnimplementedProjectServerServiceServer) testEmbeddedByValue()                              {}

// UnsafeProjectServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServerServiceServer will
// result in compilation errors.
type UnsafeProjectServerServiceServer interface {
	mustEmbedUnimplementedProjectServerServiceServer()
}

func RegisterProjectServerServiceServer(s grpc.ServiceRegistrar, srv ProjectServerServiceServer) {
	// If the following call panics, it indicates UnimplementedProjectServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectServerService_ServiceDesc, srv)
}

func _ProjectServerService_ListServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServerServiceServer).ListServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectServerService_ListServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServerServiceServer).ListServers(ctx, req.(*ListServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectServerService_GetServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServerServiceServer).GetServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectServerService_GetServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServerServiceServer).GetServer(ctx, req.(*GetServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectServerService_UpsertServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServerServiceServer).UpsertServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectServerService_UpsertServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServerServiceServer).UpsertServer(ctx, req.(*UpsertServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectServerService_DeleteServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServerServiceServer).DeleteServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectServerService_DeleteServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServerServiceServer).DeleteServer(ctx, req.(*DeleteServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectServerService_ServiceDesc is the grpc.ServiceDesc for ProjectServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logplatform.v1.ProjectServerService",
	HandlerType: (*ProjectServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServers",
			Handler:    _ProjectServerService_ListServers_Handler,
		},
		{
			MethodName: "GetServer",
			Handler:    _ProjectServerService_GetServer_Handler,
		},
		{
			MethodName: "UpsertServer",
			Handler:    _ProjectServerService_UpsertServer_Handler,
		},
		{
			MethodName: "DeleteServer",
			Handler:    _ProjectServerService_DeleteServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log_platform.proto",
}

const (
	LogSourceService_ListLogSources_FullMethodName  = "/logplatform.v1.LogSourceService/ListLogSources"
	LogSourceService_UpsertLogSource_FullMethodName = "/logplatform.v1.LogSourceService/UpsertLogSource"
	LogSourceService_DeleteLogSource_FullMethodName = "/logplatform.v1.LogSourceService/DeleteLogSource"
)

// LogSourceServiceClient is the client API for LogSourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogSourceServiceClient interface {
	ListLogSources(ctx context.Context, in *ListLogSourcesRequest, opts ...grpc.CallOption) (*ListLogSourcesResponse, error)
	UpsertLogSource(ctx context.Context, in *UpsertLogSourceRequest, opts ...grpc.CallOption) (*LogSourceItem, error)
	DeleteLogSource(ctx context.Context, in *DeleteLogSourceRequest, opts ...grpc.CallOption) (*DeleteLogSourceResponse, error)
}

type logSourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogSourceServiceClient(cc grpc.ClientConnInterface) LogSourceServiceClient {
	return &logSourceServiceClient{cc}
}

func (c *logSourceServiceClient) ListLogSources(ctx context.Context, in *ListLogSourcesRequest, opts ...grpc.CallOption) (*ListLogSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLogSourcesResponse)
	err := c.cc.Invoke(ctx, LogSourceService_ListLogSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logSourceServiceClient) UpsertLogSource(ctx context.Context, in *UpsertLogSourceRequest, opts ...grpc.CallOption) (*LogSourceItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogSourceItem)
	err := c.cc.Invoke(ctx, LogSourceService_UpsertLogSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logSourceServiceClient) DeleteLogSource(ctx context.Context, in *DeleteLogSourceRequest, opts ...grpc.CallOption) (*DeleteLogSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLogSourceResponse)
	err := c.cc.Invoke(ctx, LogSourceService_DeleteLogSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogSourceServiceServer is the server API for LogSourceService service.
// All implementations must embed UnimplementedLogSourceServiceServer
// for forward compatibility.
type LogSourceServiceServer interface {
	ListLogSources(context.Context, *ListLogSourcesRequest) (*ListLogSourcesResponse, error)
	UpsertLogSource(context.Context, *UpsertLogSourceRequest) (*LogSourceItem, error)
	DeleteLogSource(context.Context, *DeleteLogSourceRequest) (*DeleteLogSourceResponse, error)
	mustEmbedUnimplementedLogSourceServiceServer()
}

// UnimplementedLogSourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogSourceServiceServer struct{}

func (UnimplementedLogSourceServiceServer) ListLogSources(context.Context, *ListLogSourcesRequest) (*ListLogSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLogSources not implemented")
}
func (UnimplementedLogSourceServiceServer) UpsertLogSource(context.Context, *UpsertLogSourceRequest) (*LogSourceItem, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertLogSource not implemented")
}
func (UnimplementedLogSourceServiceServer) DeleteLogSource(context.Context, *DeleteLogSourceRequest) (*DeleteLogSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLogSource not implemented")
}
func (UnimplementedLogSourceServiceServer) mustEmbedUnimplementedLogSourceServiceServer() {}
func (UnimplementedLogSourceServiceServer) testEmbeddedByValue()                          {}

// UnsafeLogSourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogSourceServiceServer will
// result in compilation errors.
type UnsafeLogSourceServiceServer interface {
	mustEmbedUnimplementedLogSourceServiceServer()
}

func RegisterLogSourceServiceServer(s grpc.ServiceRegistrar, srv LogSourceServiceServer) {
	// If the following call panics, it indicates UnimplementedLogSourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogSourceService_ServiceDesc, srv)
}

func _LogSourceService_ListLogSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLogSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogSourceServiceServer).ListLogSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogSourceService_ListLogSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogSourceServiceServer).ListLogSources(ctx, req.(*ListLogSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogSourceService_UpsertLogSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertLogSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogSourceServiceServer).UpsertLogSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogSourceService_UpsertLogSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogSourceServiceServer).UpsertLogSource(ctx, req.(*UpsertLogSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogSourceService_DeleteLogSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLogSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogSourceServiceServer).DeleteLogSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogSourceService_DeleteLogSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogSourceServiceServer).DeleteLogSource(ctx, req.(*DeleteLogSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogSourceService_ServiceDesc is the grpc.ServiceDesc for LogSourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogSourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logplatform.v1.LogSourceService",
	HandlerType: (*LogSourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLogSources",
			Handler:    _LogSourceService_ListLogSources_Handler,
		},
		{
			MethodName: "UpsertLogSource",
			Handler:    _LogSourceService_UpsertLogSource_Handler,
		},
		{
			MethodName: "DeleteLogSource",
			Handler:    _LogSourceService_DeleteLogSource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log_platform.proto",
}

const (
	AgentRuntimeService_Register_FullMethodName         = "/logplatform.v1.AgentRuntimeService/Register"
	AgentRuntimeService_PublicRegister_FullMethodName   = "/logplatform.v1.AgentRuntimeService/PublicRegister"
	AgentRuntimeService_GetRuntimeConfig_FullMethodName = "/logplatform.v1.AgentRuntimeService/GetRuntimeConfig"
	AgentRuntimeService_Status_FullMethodName           = "/logplatform.v1.AgentRuntimeService/Status"
	AgentRuntimeService_Bootstrap_FullMethodName        = "/logplatform.v1.AgentRuntimeService/Bootstrap"
	AgentRuntimeService_RotateToken_FullMethodName      = "/logplatform.v1.AgentRuntimeService/RotateToken"
	AgentRuntimeService_ReportDiscovery_FullMethodName  = "/logplatform.v1.AgentRuntimeService/ReportDiscovery"
	AgentRuntimeService_ListDiscovery_FullMethodName    = "/logplatform.v1.AgentRuntimeService/ListDiscovery"
	AgentRuntimeService_IngestLogs_FullMethodName       = "/logplatform.v1.AgentRuntimeService/IngestLogs"
)

// AgentRuntimeServiceClient is the client API for AgentRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentRuntimeServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	PublicRegister(ctx context.Context, in *PublicRegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetRuntimeConfig(ctx context.Context, in *GetRuntimeConfigRequest, opts ...grpc.CallOption) (*GetRuntimeConfigResponse, error)
	Status(ctx context.Context, in *AgentStatusRequest, opts ...grpc.CallOption) (*AgentStatusResponse, error)
	Bootstrap(ctx context.Context, in *AgentBootstrapRequest, opts ...grpc.CallOption) (*AgentBootstrapResponse, error)
	RotateToken(ctx context.Context, in *AgentBootstrapRequest, opts ...grpc.CallOption) (*AgentBootstrapResponse, error)
	ReportDiscovery(ctx context.Context, in *ReportDiscoveryRequest, opts ...grpc.CallOption) (*ReportDiscoveryResponse, error)
	ListDiscovery(ctx context.Context, in *ListDiscoveryRequest, opts ...grpc.CallOption) (*ListDiscoveryResponse, error)
	IngestLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestLogsRequest, IngestLogsResponse], error)
}

type agentRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRuntimeServiceClient(cc grpc.ClientConnInterface) AgentRuntimeServiceClient {
	return &agentRuntimeServiceClient{cc}
}

func (c *agentRuntimeServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) PublicRegister(ctx context.Context, in *PublicRegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_PublicRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) GetRuntimeConfig(ctx context.Context, in *GetRuntimeConfigRequest, opts ...grpc.CallOption) (*GetRuntimeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeConfigResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_GetRuntimeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) Status(ctx context.Context, in *AgentStatusRequest, opts ...grpc.CallOption) (*AgentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentStatusResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) Bootstrap(ctx context.Context, in *AgentBootstrapRequest, opts ...grpc.CallOption) (*AgentBootstrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentBootstrapResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_Bootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) RotateToken(ctx context.Context, in *AgentBootstrapRequest, opts ...grpc.CallOption) (*AgentBootstrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentBootstrapResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_RotateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) ReportDiscovery(ctx context.Context, in *ReportDiscoveryRequest, opts ...grpc.CallOption) (*ReportDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportDiscoveryResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_ReportDiscovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) ListDiscovery(ctx context.Context, in *ListDiscoveryRequest, opts ...grpc.CallOption) (*ListDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiscoveryResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_ListDiscovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) IngestLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestLogsRequest, IngestLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRuntimeService_ServiceDesc.Streams[0], AgentRuntimeService_IngestLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestLogsRequest, IngestLogsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntimeService_IngestLogsClient = grpc.BidiStreamingClient[IngestLogsRequest, IngestLogsResponse]

// AgentRuntimeServiceServer is the server API for AgentRuntimeService service.
// All implementations must embed UnimplementedAgentRuntimeServiceServer
// for forward compatibility.
type AgentRuntimeServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	PublicRegister(context.Context, *PublicRegisterRequest) (*RegisterResponse, error)
	GetRuntimeConfig(context.Context, *GetRuntimeConfigRequest) (*GetRuntimeConfigResponse, error)
	Status(context.Context, *AgentStatusRequest) (*AgentStatusResponse, error)
	Bootstrap(context.Context, *AgentBootstrapRequest) (*AgentBootstrapResponse, error)
	RotateToken(context.Context, *AgentBootstrapRequest) (*AgentBootstrapResponse, error)
	ReportDiscovery(context.Context, *ReportDiscoveryRequest) (*ReportDiscoveryResponse, error)
	ListDiscovery(context.Context, *ListDiscoveryRequest) (*ListDiscoveryResponse, error)
	IngestLogs(grpc.BidiStreamingServer[IngestLogsRequest, IngestLogsResponse]) error
	mustEmbedUnimplementedAgentRuntimeServiceServer()
}

// UnimplementedAgentRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRuntimeServiceServer struct{}

func (UnimplementedAgentRuntimeServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) PublicRegister(context.Context, *PublicRegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublicRegister not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) GetRuntimeConfig(context.Context, *GetRuntimeConfigRequest) (*GetRuntimeConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuntimeConfig not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) Status(context.Context, *AgentStatusRequest) (*AgentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) Bootstrap(context.Context, *AgentBootstrapRequest) (*AgentBootstrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bootstrap not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) RotateToken(context.Context, *AgentBootstrapRequest) (*AgentBootstrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateToken not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) ReportDiscovery(context.Context, *ReportDiscoveryRequest) (*ReportDiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDiscovery not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) ListDiscovery(context.Context, *ListDiscoveryRequest) (*ListDiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDiscovery not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) IngestLogs(grpc.BidiStreamingServer[IngestLogsRequest, IngestLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method IngestLogs not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) mustEmbedUnimplementedAgentRuntimeServiceServer() {}
func (UnimplementedAgentRuntimeServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRuntimeServiceServer will
// result in compilation errors.
type UnsafeAgentRuntimeServiceServer interface {
	mustEmbedUnimplementedAgentRuntimeServiceServer()
}

func RegisterAgentRuntimeServiceServer(s grpc.ServiceRegistrar, srv AgentRuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRuntimeService_ServiceDesc, srv)
}

func _AgentRuntimeService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_PublicRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).PublicRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_PublicRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).PublicRegister(ctx, req.(*PublicRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_GetRuntimeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).GetRuntimeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_GetRuntimeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).GetRuntimeConfig(ctx, req.(*GetRuntimeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).Status(ctx, req.(*AgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_Bootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentBootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).Bootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_Bootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).Bootstrap(ctx, req.(*AgentBootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_RotateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentBootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).RotateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_RotateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).RotateToken(ctx, req.(*AgentBootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_ReportDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).ReportDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_ReportDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).ReportDiscovery(ctx, req.(*ReportDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_ListDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).ListDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_ListDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).ListDiscovery(ctx, req.(*ListDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_IngestLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentRuntimeServiceServer).IngestLogs(&grpc.GenericServerStream[IngestLogsRequest, IngestLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntimeService_IngestLogsServer = grpc.BidiStreamingServer[IngestLogsRequest, IngestLogsResponse]

// AgentRuntimeService_ServiceDesc is the grpc.ServiceDesc for AgentRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logplatform.v1.AgentRuntimeService",
	HandlerType: (*AgentRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentRuntimeService_Register_Handler,
		},
		{
			MethodName: "PublicRegister",
			Handler:    _AgentRuntimeService_PublicRegister_Handler,
		},
		{
			MethodName: "GetRuntimeConfig",
			Handler:    _AgentRuntimeService_GetRuntimeConfig_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _AgentRuntimeService_Status_Handler,
		},
		{
			MethodName: "Bootstrap",
			Handler:    _AgentRuntimeService_Bootstrap_Handler,
		},
		{
			MethodName: "RotateToken",
			Handler:    _AgentRuntimeService_RotateToken_Handler,
		},
		{
			MethodName: "ReportDiscovery",
			Handler:    _AgentRuntimeService_ReportDiscovery_Handler,
		},
		{
			MethodName: "ListDiscovery",
			Handler:    _AgentRuntimeService_ListDiscovery_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestLogs",
			Handler:       _AgentRuntimeService_IngestLogs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "log_platform.proto",
}
