// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: log_platform.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_log_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorInfo) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_log_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{1}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResult) Reset() {
	*x = PageResult{}
	mi := &file_log_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResult) ProtoMessage() {}

func (x *PageResult) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResult.ProtoReflect.Descriptor instead.
func (*PageResult) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{2}
}

func (x *PageResult) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResult) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResult) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ServerItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     uint64                 `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	OsType        string                 `protobuf:"bytes,6,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	OsArch        string                 `protobuf:"bytes,7,opt,name=os_arch,json=osArch,proto3" json:"os_arch,omitempty"`
	Tags          string                 `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty"`
	LastTestAt    string                 `protobuf:"bytes,9,opt,name=last_test_at,json=lastTestAt,proto3" json:"last_test_at,omitempty"`
	LastTestError string                 `protobuf:"bytes,10,opt,name=last_test_error,json=lastTestError,proto3" json:"last_test_error,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSeenAt    string                 `protobuf:"bytes,12,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	Status        int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerItem) Reset() {
	*x = ServerItem{}
	mi := &file_log_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerItem) ProtoMessage() {}

func (x *ServerItem) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerItem.ProtoReflect.Descriptor instead.
func (*ServerItem) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{3}
}

func (x *ServerItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerItem) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ServerItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerItem) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServerItem) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerItem) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *ServerItem) GetOsArch() string {
	if x != nil {
		return x.OsArch
	}
	return ""
}

func (x *ServerItem) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *ServerItem) GetLastTestAt() string {
	if x != nil {
		return x.LastTestAt
	}
	return ""
}

func (x *ServerItem) GetLastTestError() string {
	if x != nil {
		return x.LastTestError
	}
	return ""
}

func (x *ServerItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ServerItem) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *ServerItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint64                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersRequest) Reset() {
	*x = ListServersRequest{}
	mi := &file_log_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersRequest) ProtoMessage() {}

func (x *ListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersRequest.ProtoReflect.Descriptor instead.
func (*ListServersRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{4}
}

func (x *ListServersRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListServersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListServersRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ServerItem          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          *PageResult            `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersResponse) Reset() {
	*x = ListServersResponse{}
	mi := &file_log_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersResponse) ProtoMessage() {}

func (x *ListServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersResponse.ProtoReflect.Descriptor instead.
func (*ListServersResponse) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{5}
}

func (x *ListServersResponse) GetList() []*ServerItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListServersResponse) GetPage() *PageResult {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerRequest) Reset() {
	*x = GetServerRequest{}
	mi := &file_log_platform_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRequest) ProtoMessage() {}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRequest.ProtoReflect.Descriptor instead.
func (*GetServerRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{6}
}

func (x *GetServerRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpsertServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     uint64                 `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	OsType        string                 `protobuf:"bytes,6,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	Tags          string                 `protobuf:"bytes,7,opt,name=tags,proto3" json:"tags,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	AuthType      string                 `protobuf:"bytes,9,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	Username      string                 `protobuf:"bytes,10,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,11,opt,name=password,proto3" json:"password,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,12,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Passphrase    string                 `protobuf:"bytes,13,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertServerRequest) Reset() {
	*x = UpsertServerRequest{}
	mi := &file_log_platform_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertServerRequest) ProtoMessage() {}

func (x *UpsertServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertServerRequest.ProtoReflect.Descriptor instead.
func (*UpsertServerRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertServerRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpsertServerRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *UpsertServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertServerRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *UpsertServerRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *UpsertServerRequest) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *UpsertServerRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *UpsertServerRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpsertServerRequest) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *UpsertServerRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpsertServerRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpsertServerRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *UpsertServerRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type DeleteServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerRequest) Reset() {
	*x = DeleteServerRequest{}
	mi := &file_log_platform_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerRequest) ProtoMessage() {}

func (x *DeleteServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteServerRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerResponse) Reset() {
	*x = DeleteServerResponse{}
	mi := &file_log_platform_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerResponse) ProtoMessage() {}

func (x *DeleteServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteServerResponse) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteServerResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type LogSourceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceId     uint64                 `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	LogType       string                 `protobuf:"bytes,3,opt,name=log_type,json=logType,proto3" json:"log_type,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Encoding      string                 `protobuf:"bytes,5,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Timezone      string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	MultilineRule string                 `protobuf:"bytes,7,opt,name=multiline_rule,json=multilineRule,proto3" json:"multiline_rule,omitempty"`
	IncludeRegex  string                 `protobuf:"bytes,8,opt,name=include_regex,json=includeRegex,proto3" json:"include_regex,omitempty"`
	ExcludeRegex  string                 `protobuf:"bytes,9,opt,name=exclude_regex,json=excludeRegex,proto3" json:"exclude_regex,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSourceItem) Reset() {
	*x = LogSourceItem{}
	mi := &file_log_platform_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSourceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSourceItem) ProtoMessage() {}

func (x *LogSourceItem) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSourceItem.ProtoReflect.Descriptor instead.
func (*LogSourceItem) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{10}
}

func (x *LogSourceItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogSourceItem) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *LogSourceItem) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *LogSourceItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogSourceItem) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *LogSourceItem) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *LogSourceItem) GetMultilineRule() string {
	if x != nil {
		return x.MultilineRule
	}
	return ""
}

func (x *LogSourceItem) GetIncludeRegex() string {
	if x != nil {
		return x.IncludeRegex
	}
	return ""
}

func (x *LogSourceItem) GetExcludeRegex() string {
	if x != nil {
		return x.ExcludeRegex
	}
	return ""
}

func (x *LogSourceItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LogSourceItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListLogSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint64                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceId     uint64                 `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	HasServiceId  bool                   `protobuf:"varint,3,opt,name=has_service_id,json=hasServiceId,proto3" json:"has_service_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogSourcesRequest) Reset() {
	*x = ListLogSourcesRequest{}
	mi := &file_log_platform_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogSourcesRequest) ProtoMessage() {}

func (x *ListLogSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListLogSourcesRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{11}
}

func (x *ListLogSourcesRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListLogSourcesRequest) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *ListLogSourcesRequest) GetHasServiceId() bool {
	if x != nil {
		return x.HasServiceId
	}
	return false
}

func (x *ListLogSourcesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListLogSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*LogSourceItem       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          *PageResult            `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogSourcesResponse) Reset() {
	*x = ListLogSourcesResponse{}
	mi := &file_log_platform_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogSourcesResponse) ProtoMessage() {}

func (x *ListLogSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListLogSourcesResponse) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{12}
}

func (x *ListLogSourcesResponse) GetList() []*LogSourceItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListLogSourcesResponse) GetPage() *PageResult {
	if x != nil {
		return x.Page
	}
	return nil
}

type UpsertLogSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceId     uint64                 `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	LogType       string                 `protobuf:"bytes,3,opt,name=log_type,json=logType,proto3" json:"log_type,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Encoding      string                 `protobuf:"bytes,5,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Timezone      string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	MultilineRule string                 `protobuf:"bytes,7,opt,name=multiline_rule,json=multilineRule,proto3" json:"multiline_rule,omitempty"`
	IncludeRegex  string                 `protobuf:"bytes,8,opt,name=include_regex,json=includeRegex,proto3" json:"include_regex,omitempty"`
	ExcludeRegex  string                 `protobuf:"bytes,9,opt,name=exclude_regex,json=excludeRegex,proto3" json:"exclude_regex,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertLogSourceRequest) Reset() {
	*x = UpsertLogSourceRequest{}
	mi := &file_log_platform_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertLogSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertLogSourceRequest) ProtoMessage() {}

func (x *UpsertLogSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertLogSourceRequest.ProtoReflect.Descriptor instead.
func (*UpsertLogSourceRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertLogSourceRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpsertLogSourceRequest) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *UpsertLogSourceRequest) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *UpsertLogSourceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpsertLogSourceRequest) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *UpsertLogSourceRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UpsertLogSourceRequest) GetMultilineRule() string {
	if x != nil {
		return x.MultilineRule
	}
	return ""
}

func (x *UpsertLogSourceRequest) GetIncludeRegex() string {
	if x != nil {
		return x.IncludeRegex
	}
	return ""
}

func (x *UpsertLogSourceRequest) GetExcludeRegex() string {
	if x != nil {
		return x.ExcludeRegex
	}
	return ""
}

func (x *UpsertLogSourceRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeleteLogSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLogSourceRequest) Reset() {
	*x = DeleteLogSourceRequest{}
	mi := &file_log_platform_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLogSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLogSourceRequest) ProtoMessage() {}

func (x *DeleteLogSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLogSourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteLogSourceRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteLogSourceRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteLogSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLogSourceResponse) Reset() {
	*x = DeleteLogSourceResponse{}
	mi := &file_log_platform_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLogSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLogSourceResponse) ProtoMessage() {}

func (x *DeleteLogSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLogSourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteLogSourceResponse) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteLogSourceResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type AgentDiscoveryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastSeenAt    string                 `protobuf:"bytes,4,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDiscoveryItem) Reset() {
	*x = AgentDiscoveryItem{}
	mi := &file_log_platform_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDiscoveryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDiscoveryItem) ProtoMessage() {}

func (x *AgentDiscoveryItem) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDiscoveryItem.ProtoReflect.Descriptor instead.
func (*AgentDiscoveryItem) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{16}
}

func (x *AgentDiscoveryItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AgentDiscoveryItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AgentDiscoveryItem) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *AgentDiscoveryItem) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint64                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServerId      uint64                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_log_platform_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *RegisterRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PublicRegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       uint64                 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	RegisterSecret string                 `protobuf:"bytes,4,opt,name=register_secret,json=registerSecret,proto3" json:"register_secret,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublicRegisterRequest) Reset() {
	*x = PublicRegisterRequest{}
	mi := &file_log_platform_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicRegisterRequest) ProtoMessage() {}

func (x *PublicRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicRegisterRequest.ProtoReflect.Descriptor instead.
func (*PublicRegisterRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{18}
}

func (x *PublicRegisterRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *PublicRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublicRegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PublicRegisterRequest) GetRegisterSecret() string {
	if x != nil {
		return x.RegisterSecret
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint64                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AgentId       uint64                 `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_log_platform_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterResponse) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *RegisterResponse) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetRuntimeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeConfigRequest) Reset() {
	*x = GetRuntimeConfigRequest{}
	mi := &file_log_platform_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeConfigRequest) ProtoMessage() {}

func (x *GetRuntimeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeConfigRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeConfigRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{20}
}

func (x *GetRuntimeConfigRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RuntimeSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogSourceId   uint64                 `protobuf:"varint,1,opt,name=log_source_id,json=logSourceId,proto3" json:"log_source_id,omitempty"`
	LogType       string                 `protobuf:"bytes,2,opt,name=log_type,json=logType,proto3" json:"log_type,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeSource) Reset() {
	*x = RuntimeSource{}
	mi := &file_log_platform_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSource) ProtoMessage() {}

func (x *RuntimeSource) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSource.ProtoReflect.Descriptor instead.
func (*RuntimeSource) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{21}
}

func (x *RuntimeSource) GetLogSourceId() uint64 {
	if x != nil {
		return x.LogSourceId
	}
	return 0
}

func (x *RuntimeSource) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *RuntimeSource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetRuntimeConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint64                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServerId      uint64                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Sources       []*RuntimeSource       `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeConfigResponse) Reset() {
	*x = GetRuntimeConfigResponse{}
	mi := &file_log_platform_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeConfigResponse) ProtoMessage() {}

func (x *GetRuntimeConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeConfigResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeConfigResponse) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{22}
}

func (x *GetRuntimeConfigResponse) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *GetRuntimeConfigResponse) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *GetRuntimeConfigResponse) GetSources() []*RuntimeSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

type AgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint64                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServerId      uint64                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	LogSourceId   uint64                 `protobuf:"varint,3,opt,name=log_source_id,json=logSourceId,proto3" json:"log_source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusRequest) Reset() {
	*x = AgentStatusRequest{}
	mi := &file_log_platform_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusRequest) ProtoMessage() {}

func (x *AgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusRequest.ProtoReflect.Descriptor instead.
func (*AgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{23}
}

func (x *AgentStatusRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *AgentStatusRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *AgentStatusRequest) GetLogSourceId() uint64 {
	if x != nil {
		return x.LogSourceId
	}
	return 0
}

type AgentStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         uint64                 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	LogSourceId      uint64                 `protobuf:"varint,2,opt,name=log_source_id,json=logSourceId,proto3" json:"log_source_id,omitempty"`
	AgentId          uint64                 `protobuf:"varint,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HasAgentId       bool                   `protobuf:"varint,4,opt,name=has_agent_id,json=hasAgentId,proto3" json:"has_agent_id,omitempty"`
	Name             string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Version          string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	LastSeenAt       string                 `protobuf:"bytes,7,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	Online           bool                   `protobuf:"varint,8,opt,name=online,proto3" json:"online,omitempty"`
	RecentPublishing bool                   `protobuf:"varint,9,opt,name=recent_publishing,json=recentPublishing,proto3" json:"recent_publishing,omitempty"`
	ModeHint         string                 `protobuf:"bytes,10,opt,name=mode_hint,json=modeHint,proto3" json:"mode_hint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentStatusResponse) Reset() {
	*x = AgentStatusResponse{}
	mi := &file_log_platform_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusResponse) ProtoMessage() {}

func (x *AgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusResponse.ProtoReflect.Descriptor instead.
func (*AgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{24}
}

func (x *AgentStatusResponse) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *AgentStatusResponse) GetLogSourceId() uint64 {
	if x != nil {
		return x.LogSourceId
	}
	return 0
}

func (x *AgentStatusResponse) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentStatusResponse) GetHasAgentId() bool {
	if x != nil {
		return x.HasAgentId
	}
	return false
}

func (x *AgentStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentStatusResponse) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *AgentStatusResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *AgentStatusResponse) GetRecentPublishing() bool {
	if x != nil {
		return x.RecentPublishing
	}
	return false
}

func (x *AgentStatusResponse) GetModeHint() string {
	if x != nil {
		return x.ModeHint
	}
	return ""
}

type AgentBootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint64                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServerId      uint64                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	LogSourceId   uint64                 `protobuf:"varint,3,opt,name=log_source_id,json=logSourceId,proto3" json:"log_source_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	PlatformUrl   string                 `protobuf:"bytes,6,opt,name=platform_url,json=platformUrl,proto3" json:"platform_url,omitempty"`
	AgentName     string                 `protobuf:"bytes,7,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentVer      string                 `protobuf:"bytes,8,opt,name=agent_ver,json=agentVer,proto3" json:"agent_ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentBootstrapRequest) Reset() {
	*x = AgentBootstrapRequest{}
	mi := &file_log_platform_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentBootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentBootstrapRequest) ProtoMessage() {}

func (x *AgentBootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentBootstrapRequest.ProtoReflect.Descriptor instead.
func (*AgentBootstrapRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{25}
}

func (x *AgentBootstrapRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *AgentBootstrapRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *AgentBootstrapRequest) GetLogSourceId() uint64 {
	if x != nil {
		return x.LogSourceId
	}
	return 0
}

func (x *AgentBootstrapRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *AgentBootstrapRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AgentBootstrapRequest) GetPlatformUrl() string {
	if x != nil {
		return x.PlatformUrl
	}
	return ""
}

func (x *AgentBootstrapRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentBootstrapRequest) GetAgentVer() string {
	if x != nil {
		return x.AgentVer
	}
	return ""
}

type AgentBootstrapResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token          string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	RunCommand     string                 `protobuf:"bytes,3,opt,name=run_command,json=runCommand,proto3" json:"run_command,omitempty"`
	SystemdService string                 `protobuf:"bytes,4,opt,name=systemd_service,json=systemdService,proto3" json:"systemd_service,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentBootstrapResponse) Reset() {
	*x = AgentBootstrapResponse{}
	mi := &file_log_platform_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentBootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentBootstrapResponse) ProtoMessage() {}

func (x *AgentBootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentBootstrapResponse.ProtoReflect.Descriptor instead.
func (*AgentBootstrapResponse) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{26}
}

func (x *AgentBootstrapResponse) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentBootstrapResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AgentBootstrapResponse) GetRunCommand() string {
	if x != nil {
		return x.RunCommand
	}
	return ""
}

func (x *AgentBootstrapResponse) GetSystemdService() string {
	if x != nil {
		return x.SystemdService
	}
	return ""
}

type ReportDiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Items         []*AgentDiscoveryItem  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDiscoveryRequest) Reset() {
	*x = ReportDiscoveryRequest{}
	mi := &file_log_platform_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDiscoveryRequest) ProtoMessage() {}

func (x *ReportDiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDiscoveryRequest.ProtoReflect.Descriptor instead.
func (*ReportDiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{27}
}

func (x *ReportDiscoveryRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReportDiscoveryRequest) GetItems() []*AgentDiscoveryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReportDiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDiscoveryResponse) Reset() {
	*x = ReportDiscoveryResponse{}
	mi := &file_log_platform_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDiscoveryResponse) ProtoMessage() {}

func (x *ReportDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*ReportDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{28}
}

func (x *ReportDiscoveryResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type ListDiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint64                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServerId      uint64                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiscoveryRequest) Reset() {
	*x = ListDiscoveryRequest{}
	mi := &file_log_platform_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiscoveryRequest) ProtoMessage() {}

func (x *ListDiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiscoveryRequest.ProtoReflect.Descriptor instead.
func (*ListDiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{29}
}

func (x *ListDiscoveryRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListDiscoveryRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ListDiscoveryRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListDiscoveryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AgentDiscoveryItem  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiscoveryResponse) Reset() {
	*x = ListDiscoveryResponse{}
	mi := &file_log_platform_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiscoveryResponse) ProtoMessage() {}

func (x *ListDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*ListDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{30}
}

func (x *ListDiscoveryResponse) GetList() []*AgentDiscoveryItem {
	if x != nil {
		return x.List
	}
	return nil
}

type IngestEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEntry) Reset() {
	*x = IngestEntry{}
	mi := &file_log_platform_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEntry) ProtoMessage() {}

func (x *IngestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEntry.ProtoReflect.Descriptor instead.
func (*IngestEntry) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{31}
}

func (x *IngestEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *IngestEntry) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type IngestLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint64                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServerId      uint64                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	LogSourceId   uint64                 `protobuf:"varint,3,opt,name=log_source_id,json=logSourceId,proto3" json:"log_source_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Entries       []*IngestEntry         `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestLogsRequest) Reset() {
	*x = IngestLogsRequest{}
	mi := &file_log_platform_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestLogsRequest) ProtoMessage() {}

func (x *IngestLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestLogsRequest.ProtoReflect.Descriptor instead.
func (*IngestLogsRequest) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{32}
}

func (x *IngestLogsRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *IngestLogsRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *IngestLogsRequest) GetLogSourceId() uint64 {
	if x != nil {
		return x.LogSourceId
	}
	return 0
}

func (x *IngestLogsRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *IngestLogsRequest) GetEntries() []*IngestEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type IngestLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	TsUnixMs      int64                  `protobuf:"varint,2,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestLogsResponse) Reset() {
	*x = IngestLogsResponse{}
	mi := &file_log_platform_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestLogsResponse) ProtoMessage() {}

func (x *IngestLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_platform_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestLogsResponse.ProtoReflect.Descriptor instead.
func (*IngestLogsResponse) Descriptor() ([]byte, []int) {
	return file_log_platform_proto_rawDescGZIP(), []int{33}
}

func (x *IngestLogsResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *IngestLogsResponse) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

var File_log_platform_proto protoreflect.FileDescriptor

const file_log_platform_proto_rawDesc = "" +
	"\n" +
	"\x12log_platform.proto\x12\x0elogplatform.v1\"9\n" +
	"\tErrorInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"S\n" +
	"\n" +
	"PageResult\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xe0\x02\n" +
	"\n" +
	"ServerItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x04R\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x17\n" +
	"\aos_type\x18\x06 \x01(\tR\x06osType\x12\x17\n" +
	"\aos_arch\x18\a \x01(\tR\x06osArch\x12\x12\n" +
	"\x04tags\x18\b \x01(\tR\x04tags\x12 \n" +
	"\flast_test_at\x18\t \x01(\tR\n" +
	"lastTestAt\x12&\n" +
	"\x0flast_test_error\x18\n" +
	" \x01(\tR\rlastTestError\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12 \n" +
	"\flast_seen_at\x18\f \x01(\tR\n" +
	"lastSeenAt\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\"~\n" +
	"\x12ListServersRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x04R\tprojectId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.logplatform.v1.PageRequestR\x04page\"u\n" +
	"\x13ListServersResponse\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.logplatform.v1.ServerItemR\x04list\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.logplatform.v1.PageResultR\x04page\"\"\n" +
	"\x10GetServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xdb\x02\n" +
	"\x13UpsertServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x04R\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x17\n" +
	"\aos_type\x18\x06 \x01(\tR\x06osType\x12\x12\n" +
	"\x04tags\x18\a \x01(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1b\n" +
	"\tauth_type\x18\t \x01(\tR\bauthType\x12\x1a\n" +
	"\busername\x18\n" +
	" \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\v \x01(\tR\bpassword\x12\x1f\n" +
	"\vprivate_key\x18\f \x01(\tR\n" +
	"privateKey\x12\x1e\n" +
	"\n" +
	"passphrase\x18\r \x01(\tR\n" +
	"passphrase\"%\n" +
	"\x13DeleteServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"0\n" +
	"\x14DeleteServerResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xcd\x02\n" +
	"\rLogSourceItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\x04R\tserviceId\x12\x19\n" +
	"\blog_type\x18\x03 \x01(\tR\alogType\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1a\n" +
	"\bencoding\x18\x05 \x01(\tR\bencoding\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\x12%\n" +
	"\x0emultiline_rule\x18\a \x01(\tR\rmultilineRule\x12#\n" +
	"\rinclude_regex\x18\b \x01(\tR\fincludeRegex\x12#\n" +
	"\rexclude_regex\x18\t \x01(\tR\fexcludeRegex\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"\xac\x01\n" +
	"\x15ListLogSourcesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x04R\tprojectId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\x04R\tserviceId\x12$\n" +
	"\x0ehas_service_id\x18\x03 \x01(\bR\fhasServiceId\x12/\n" +
	"\x04page\x18\x04 \x01(\v2\x1b.logplatform.v1.PageRequestR\x04page\"{\n" +
	"\x16ListLogSourcesResponse\x121\n" +
	"\x04list\x18\x01 \x03(\v2\x1d.logplatform.v1.LogSourceItemR\x04list\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.logplatform.v1.PageResultR\x04page\"\xb7\x02\n" +
	"\x16UpsertLogSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\x04R\tserviceId\x12\x19\n" +
	"\blog_type\x18\x03 \x01(\tR\alogType\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1a\n" +
	"\bencoding\x18\x05 \x01(\tR\bencoding\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\x12%\n" +
	"\x0emultiline_rule\x18\a \x01(\tR\rmultilineRule\x12#\n" +
	"\rinclude_regex\x18\b \x01(\tR\fincludeRegex\x12#\n" +
	"\rexclude_regex\x18\t \x01(\tR\fexcludeRegex\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\"(\n" +
	"\x16DeleteLogSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"3\n" +
	"\x17DeleteLogSourceResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xdf\x01\n" +
	"\x12AgentDiscoveryItem\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12C\n" +
	"\x05extra\x18\x03 \x03(\v2-.logplatform.v1.AgentDiscoveryItem.ExtraEntryR\x05extra\x12 \n" +
	"\flast_seen_at\x18\x04 \x01(\tR\n" +
	"lastSeenAt\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x04R\tprojectId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x04R\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\x8b\x01\n" +
	"\x15PublicRegisterRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x04R\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12'\n" +
	"\x0fregister_secret\x18\x04 \x01(\tR\x0eregisterSecret\"b\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x04R\tprojectId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\x04R\aagentId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"/\n" +
	"\x17GetRuntimeConfigRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"b\n" +
	"\rRuntimeSource\x12\"\n" +
	"\rlog_source_id\x18\x01 \x01(\x04R\vlogSourceId\x12\x19\n" +
	"\blog_type\x18\x02 \x01(\tR\alogType\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\x8f\x01\n" +
	"\x18GetRuntimeConfigResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x04R\tprojectId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x04R\bserverId\x127\n" +
	"\asources\x18\x03 \x03(\v2\x1d.logplatform.v1.RuntimeSourceR\asources\"t\n" +
	"\x12AgentStatusRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x04R\tprojectId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x04R\bserverId\x12\"\n" +
	"\rlog_source_id\x18\x03 \x01(\x04R\vlogSourceId\"\xc5\x02\n" +
	"\x13AgentStatusResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x04R\bserverId\x12\"\n" +
	"\rlog_source_id\x18\x02 \x01(\x04R\vlogSourceId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\x04R\aagentId\x12 \n" +
	"\fhas_agent_id\x18\x04 \x01(\bR\n" +
	"hasAgentId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12 \n" +
	"\flast_seen_at\x18\a \x01(\tR\n" +
	"lastSeenAt\x12\x16\n" +
	"\x06online\x18\b \x01(\bR\x06online\x12+\n" +
	"\x11recent_publishing\x18\t \x01(\bR\x10recentPublishing\x12\x1b\n" +
	"\tmode_hint\x18\n" +
	" \x01(\tR\bmodeHint\"\x8b\x02\n" +
	"\x15AgentBootstrapRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x04R\tprojectId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x04R\bserverId\x12\"\n" +
	"\rlog_source_id\x18\x03 \x01(\x04R\vlogSourceId\x12\x1f\n" +
	"\vsource_type\x18\x04 \x01(\tR\n" +
	"sourceType\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12!\n" +
	"\fplatform_url\x18\x06 \x01(\tR\vplatformUrl\x12\x1d\n" +
	"\n" +
	"agent_name\x18\a \x01(\tR\tagentName\x12\x1b\n" +
	"\tagent_ver\x18\b \x01(\tR\bagentVer\"\x93\x01\n" +
	"\x16AgentBootstrapResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1f\n" +
	"\vrun_command\x18\x03 \x01(\tR\n" +
	"runCommand\x12'\n" +
	"\x0fsystemd_service\x18\x04 \x01(\tR\x0esystemdService\"h\n" +
	"\x16ReportDiscoveryRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x128\n" +
	"\x05items\x18\x02 \x03(\v2\".logplatform.v1.AgentDiscoveryItemR\x05items\"5\n" +
	"\x17ReportDiscoveryResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\"|\n" +
	"\x14ListDiscoveryRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x04R\tprojectId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x04R\bserverId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"O\n" +
	"\x15ListDiscoveryResponse\x126\n" +
	"\x04list\x18\x01 \x03(\v2\".logplatform.v1.AgentDiscoveryItemR\x04list\">\n" +
	"\vIngestEntry\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\"\xbc\x01\n" +
	"\x11IngestLogsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x04R\tprojectId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x04R\bserverId\x12\"\n" +
	"\rlog_source_id\x18\x03 \x01(\x04R\vlogSourceId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x125\n" +
	"\aentries\x18\x05 \x03(\v2\x1b.logplatform.v1.IngestEntryR\aentries\"D\n" +
	"\x12IngestLogsResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x02 \x01(\x03R\btsUnixMs2\xe5\x02\n" +
	"\x14ProjectServerService\x12V\n" +
	"\vListServers\x12\".logplatform.v1.ListServersRequest\x1a#.logplatform.v1.ListServersResponse\x12I\n" +
	"\tGetServer\x12 .logplatform.v1.GetServerRequest\x1a\x1a.logplatform.v1.ServerItem\x12O\n" +
	"\fUpsertServer\x12#.logplatform.v1.UpsertServerRequest\x1a\x1a.logplatform.v1.ServerItem\x12Y\n" +
	"\fDeleteServer\x12#.logplatform.v1.DeleteServerRequest\x1a$.logplatform.v1.DeleteServerResponse2\xb1\x02\n" +
	"\x10LogSourceService\x12_\n" +
	"\x0eListLogSources\x12%.logplatform.v1.ListLogSourcesRequest\x1a&.logplatform.v1.ListLogSourcesResponse\x12X\n" +
	"\x0fUpsertLogSource\x12&.logplatform.v1.UpsertLogSourceRequest\x1a\x1d.logplatform.v1.LogSourceItem\x12b\n" +
	"\x0fDeleteLogSource\x12&.logplatform.v1.DeleteLogSourceRequest\x1a'.logplatform.v1.DeleteLogSourceResponse2\xce\x06\n" +
	"\x13AgentRuntimeService\x12M\n" +
	"\bRegister\x12\x1f.logplatform.v1.RegisterRequest\x1a .logplatform.v1.RegisterResponse\x12Y\n" +
	"\x0ePublicRegister\x12%.logplatform.v1.PublicRegisterRequest\x1a .logplatform.v1.RegisterResponse\x12e\n" +
	"\x10GetRuntimeConfig\x12'.logplatform.v1.GetRuntimeConfigRequest\x1a(.logplatform.v1.GetRuntimeConfigResponse\x12Q\n" +
	"\x06Status\x12\".logplatform.v1.AgentStatusRequest\x1a#.logplatform.v1.AgentStatusResponse\x12Z\n" +
	"\tBootstrap\x12%.logplatform.v1.AgentBootstrapRequest\x1a&.logplatform.v1.AgentBootstrapResponse\x12\\\n" +
	"\vRotateToken\x12%.logplatform.v1.AgentBootstrapRequest\x1a&.logplatform.v1.AgentBootstrapResponse\x12b\n" +
	"\x0fReportDiscovery\x12&.logplatform.v1.ReportDiscoveryRequest\x1a'.logplatform.v1.ReportDiscoveryResponse\x12\\\n" +
	"\rListDiscovery\x12$.logplatform.v1.ListDiscoveryRequest\x1a%.logplatform.v1.ListDiscoveryResponse\x12W\n" +
	"\n" +
	"IngestLogs\x12!.logplatform.v1.IngestLogsRequest\x1a\".logplatform.v1.IngestLogsResponse(\x010\x01B\"Z yunshu/internal/grpc/proto/pb;pbb\x06proto3"

var (
	file_log_platform_proto_rawDescOnce sync.Once
	file_log_platform_proto_rawDescData []byte
)

func file_log_platform_proto_rawDescGZIP() []byte {
	file_log_platform_proto_rawDescOnce.Do(func() {
		file_log_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_platform_proto_rawDesc), len(file_log_platform_proto_rawDesc)))
	})
	return file_log_platform_proto_rawDescData
}

var file_log_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_log_platform_proto_goTypes = []any{
	(*ErrorInfo)(nil),                // 0: logplatform.v1.ErrorInfo
	(*PageRequest)(nil),              // 1: logplatform.v1.PageRequest
	(*PageResult)(nil),               // 2: logplatform.v1.PageResult
	(*ServerItem)(nil),               // 3: logplatform.v1.ServerItem
	(*ListServersRequest)(nil),       // 4: logplatform.v1.ListServersRequest
	(*ListServersResponse)(nil),      // 5: logplatform.v1.ListServersResponse
	(*GetServerRequest)(nil),         // 6: logplatform.v1.GetServerRequest
	(*UpsertServerRequest)(nil),      // 7: logplatform.v1.UpsertServerRequest
	(*DeleteServerRequest)(nil),      // 8: logplatform.v1.DeleteServerRequest
	(*DeleteServerResponse)(nil),     // 9: logplatform.v1.DeleteServerResponse
	(*LogSourceItem)(nil),            // 10: logplatform.v1.LogSourceItem
	(*ListLogSourcesRequest)(nil),    // 11: logplatform.v1.ListLogSourcesRequest
	(*ListLogSourcesResponse)(nil),   // 12: logplatform.v1.ListLogSourcesResponse
	(*UpsertLogSourceRequest)(nil),   // 13: logplatform.v1.UpsertLogSourceRequest
	(*DeleteLogSourceRequest)(nil),   // 14: logplatform.v1.DeleteLogSourceRequest
	(*DeleteLogSourceResponse)(nil),  // 15: logplatform.v1.DeleteLogSourceResponse
	(*AgentDiscoveryItem)(nil),       // 16: logplatform.v1.AgentDiscoveryItem
	(*RegisterRequest)(nil),          // 17: logplatform.v1.RegisterRequest
	(*PublicRegisterRequest)(nil),    // 18: logplatform.v1.PublicRegisterRequest
	(*RegisterResponse)(nil),         // 19: logplatform.v1.RegisterResponse
	(*GetRuntimeConfigRequest)(nil),  // 20: logplatform.v1.GetRuntimeConfigRequest
	(*RuntimeSource)(nil),            // 21: logplatform.v1.RuntimeSource
	(*GetRuntimeConfigResponse)(nil), // 22: logplatform.v1.GetRuntimeConfigResponse
	(*AgentStatusRequest)(nil),       // 23: logplatform.v1.AgentStatusRequest
	(*AgentStatusResponse)(nil),      // 24: logplatform.v1.AgentStatusResponse
	(*AgentBootstrapRequest)(nil),    // 25: logplatform.v1.AgentBootstrapRequest
	(*AgentBootstrapResponse)(nil),   // 26: logplatform.v1.AgentBootstrapResponse
	(*ReportDiscoveryRequest)(nil),   // 27: logplatform.v1.ReportDiscoveryRequest
	(*ReportDiscoveryResponse)(nil),  // 28: logplatform.v1.ReportDiscoveryResponse
	(*ListDiscoveryRequest)(nil),     // 29: logplatform.v1.ListDiscoveryRequest
	(*ListDiscoveryResponse)(nil),    // 30: logplatform.v1.ListDiscoveryResponse
	(*IngestEntry)(nil),              // 31: logplatform.v1.IngestEntry
	(*IngestLogsRequest)(nil),        // 32: logplatform.v1.IngestLogsRequest
	(*IngestLogsResponse)(nil),       // 33: logplatform.v1.IngestLogsResponse
	nil,                              // 34: logplatform.v1.AgentDiscoveryItem.ExtraEntry
}
var file_log_platform_proto_depIdxs = []int32{
	1,  // 0: logplatform.v1.ListServersRequest.page:type_name -> logplatform.v1.PageRequest
	3,  // 1: logplatform.v1.ListServersResponse.list:type_name -> logplatform.v1.ServerItem
	2,  // 2: logplatform.v1.ListServersResponse.page:type_name -> logplatform.v1.PageResult
	1,  // 3: logplatform.v1.ListLogSourcesRequest.page:type_name -> logplatform.v1.PageRequest
	10, // 4: logplatform.v1.ListLogSourcesResponse.list:type_name -> logplatform.v1.LogSourceItem
	2,  // 5: logplatform.v1.ListLogSourcesResponse.page:type_name -> logplatform.v1.PageResult
	34, // 6: logplatform.v1.AgentDiscoveryItem.extra:type_name -> logplatform.v1.AgentDiscoveryItem.ExtraEntry
	21, // 7: logplatform.v1.GetRuntimeConfigResponse.sources:type_name -> logplatform.v1.RuntimeSource
	16, // 8: logplatform.v1.ReportDiscoveryRequest.items:type_name -> logplatform.v1.AgentDiscoveryItem
	16, // 9: logplatform.v1.ListDiscoveryResponse.list:type_name -> logplatform.v1.AgentDiscoveryItem
	31, // 10: logplatform.v1.IngestLogsRequest.entries:type_name -> logplatform.v1.IngestEntry
	4,  // 11: logplatform.v1.ProjectServerService.ListServers:input_type -> logplatform.v1.ListServersRequest
	6,  // 12: logplatform.v1.ProjectServerService.GetServer:input_type -> logplatform.v1.GetServerRequest
	7,  // 13: logplatform.v1.ProjectServerService.UpsertServer:input_type -> logplatform.v1.UpsertServerRequest
	8,  // 14: logplatform.v1.ProjectServerService.DeleteServer:input_type -> logplatform.v1.DeleteServerRequest
	11, // 15: logplatform.v1.LogSourceService.ListLogSources:input_type -> logplatform.v1.ListLogSourcesRequest
	13, // 16: logplatform.v1.LogSourceService.UpsertLogSource:input_type -> logplatform.v1.UpsertLogSourceRequest
	14, // 17: logplatform.v1.LogSourceService.DeleteLogSource:input_type -> logplatform.v1.DeleteLogSourceRequest
	17, // 18: logplatform.v1.AgentRuntimeService.Register:input_type -> logplatform.v1.RegisterRequest
	18, // 19: logplatform.v1.AgentRuntimeService.PublicRegister:input_type -> logplatform.v1.PublicRegisterRequest
	20, // 20: logplatform.v1.AgentRuntimeService.GetRuntimeConfig:input_type -> logplatform.v1.GetRuntimeConfigRequest
	23, // 21: logplatform.v1.AgentRuntimeService.Status:input_type -> logplatform.v1.AgentStatusRequest
	25, // 22: logplatform.v1.AgentRuntimeService.Bootstrap:input_type -> logplatform.v1.AgentBootstrapRequest
	25, // 23: logplatform.v1.AgentRuntimeService.RotateToken:input_type -> logplatform.v1.AgentBootstrapRequest
	27, // 24: logplatform.v1.AgentRuntimeService.ReportDiscovery:input_type -> logplatform.v1.ReportDiscoveryRequest
	29, // 25: logplatform.v1.AgentRuntimeService.ListDiscovery:input_type -> logplatform.v1.ListDiscoveryRequest
	32, // 26: logplatform.v1.AgentRuntimeService.IngestLogs:input_type -> logplatform.v1.IngestLogsRequest
	5,  // 27: logplatform.v1.ProjectServerService.ListServers:output_type -> logplatform.v1.ListServersResponse
	3,  // 28: logplatform.v1.ProjectServerService.GetServer:output_type -> logplatform.v1.ServerItem
	3,  // 29: logplatform.v1.ProjectServerService.UpsertServer:output_type -> logplatform.v1.ServerItem
	9,  // 30: logplatform.v1.ProjectServerService.DeleteServer:output_type -> logplatform.v1.DeleteServerResponse
	12, // 31: logplatform.v1.LogSourceService.ListLogSources:output_type -> logplatform.v1.ListLogSourcesResponse
	10, // 32: logplatform.v1.LogSourceService.UpsertLogSource:output_type -> logplatform.v1.LogSourceItem
	15, // 33: logplatform.v1.LogSourceService.DeleteLogSource:output_type -> logplatform.v1.DeleteLogSourceResponse
	19, // 34: logplatform.v1.AgentRuntimeService.Register:output_type -> logplatform.v1.RegisterResponse
	19, // 35: logplatform.v1.AgentRuntimeService.PublicRegister:output_type -> logplatform.v1.RegisterResponse
	22, // 36: logplatform.v1.AgentRuntimeService.GetRuntimeConfig:output_type -> logplatform.v1.GetRuntimeConfigResponse
	24, // 37: logplatform.v1.AgentRuntimeService.Status:output_type -> logplatform.v1.AgentStatusResponse
	26, // 38: logplatform.v1.AgentRuntimeService.Bootstrap:output_type -> logplatform.v1.AgentBootstrapResponse
	26, // 39: logplatform.v1.AgentRuntimeService.RotateToken:output_type -> logplatform.v1.AgentBootstrapResponse
	28, // 40: logplatform.v1.AgentRuntimeService.ReportDiscovery:output_type -> logplatform.v1.ReportDiscoveryResponse
	30, // 41: logplatform.v1.AgentRuntimeService.ListDiscovery:output_type -> logplatform.v1.ListDiscoveryResponse
	33, // 42: logplatform.v1.AgentRuntimeService.IngestLogs:output_type -> logplatform.v1.IngestLogsResponse
	27, // [27:43] is the sub-list for method output_type
	11, // [11:27] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_log_platform_proto_init() }
func file_log_platform_proto_init() {
	if File_log_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_platform_proto_rawDesc), len(file_log_platform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_log_platform_proto_goTypes,
		DependencyIndexes: file_log_platform_proto_depIdxs,
		MessageInfos:      file_log_platform_proto_msgTypes,
	}.Build()
	File_log_platform_proto = out.File
	file_log_platform_proto_goTypes = nil
	file_log_platform_proto_depIdxs = nil
}
