export type DictTypeOption = { label: string; value: string };

export const PROJECT_DICT_TYPE_OPTIONS: DictTypeOption[] = [
  { label: "通用状态（common_status）", value: "common_status" },
  { label: "告警通道类型（alert_channel_type）", value: "alert_channel_type" },
  { label: "告警 Webhook URL（alert_webhook_url）", value: "alert_webhook_url" },
  { label: "企业微信 Webhook URL（wecom_webhook_url）", value: "wecom_webhook_url" },
  { label: "钉钉 Webhook URL（dingtalk_webhook_url）", value: "dingtalk_webhook_url" },
  { label: "企业微信通知模式（wecom_notify_mode）", value: "wecom_notify_mode" },
  { label: "钉钉通知模式（dingtalk_notify_mode）", value: "dingtalk_notify_mode" },
  { label: "告警级别（alert_severity）", value: "alert_severity" },
  { label: "告警数据源地址（alert_datasource_base_url）", value: "alert_datasource_base_url" },
  { label: "告警数据源账号（alert_datasource_basic_user）", value: "alert_datasource_basic_user" },
  { label: "告警静默匹配键（alert_silence_matcher_name）", value: "alert_silence_matcher_name" },
  { label: "PromQL 标签键（alert_promql_label_key）", value: "alert_promql_label_key" },
  { label: "阈值单位（alert_threshold_unit）", value: "alert_threshold_unit" },
  { label: "告警 Webhook Token（alert_webhook_token）", value: "alert_webhook_token" },
  { label: "告警 Prometheus URL（alert_enrich_prometheus_url）", value: "alert_enrich_prometheus_url" },
  { label: "告警 Prometheus Token（alert_enrich_prometheus_token）", value: "alert_enrich_prometheus_token" },
  { label: "邮件主机（mail_host）", value: "mail_host" },
  { label: "邮件端口（mail_port）", value: "mail_port" },
  { label: "邮件用户名（mail_username）", value: "mail_username" },
  { label: "邮件密码（mail_password）", value: "mail_password" },
  { label: "发件邮箱（mail_from_email）", value: "mail_from_email" },
  { label: "发件名称（mail_from_name）", value: "mail_from_name" },
  { label: "是否启用 TLS（mail_use_tls）", value: "mail_use_tls" },
  { label: "企业微信 corpID（wecom_corp_id）", value: "wecom_corp_id" },
  { label: "企业微信 corpSecret（wecom_corp_secret）", value: "wecom_corp_secret" },
  { label: "企业微信 agentId（wecom_agent_id）", value: "wecom_agent_id" },
  { label: "钉钉 appKey（dingtalk_app_key）", value: "dingtalk_app_key" },
  { label: "钉钉 appSecret（dingtalk_app_secret）", value: "dingtalk_app_secret" },
  { label: "钉钉 chatId（dingtalk_chat_id）", value: "dingtalk_chat_id" },
  { label: "钉钉 signSecret（dingtalk_sign_secret）", value: "dingtalk_sign_secret" },
  { label: "Kubeconfig 模板（k8s_kubeconfig_template）", value: "k8s_kubeconfig_template" },
  { label: "服务器分组分类（server_group_category）", value: "server_group_category" },
  { label: "服务器系统类型（server_os_type）", value: "server_os_type" },
  { label: "服务器认证类型（server_auth_type）", value: "server_auth_type" },
  { label: "服务器 SSH 用户名模板（server_ssh_username）", value: "server_ssh_username" },
  { label: "服务器 SSH 密码模板（server_ssh_password）", value: "server_ssh_password" },
  { label: "服务器端口模板（server_port）", value: "server_port" },
  { label: "日志源类型（log_source_type）", value: "log_source_type" },
  { label: "Agent 健康状态（log_agent_health_status）", value: "log_agent_health_status" },
  { label: "平台地址（agent_platform_url）", value: "agent_platform_url" },
];

