package router

import (
	"github.com/gin-gonic/gin"
)

func registerK8sRoutes(api *gin.RouterGroup, d *routeDeps) {
	// Kubernetes cluster management (Kom SDK)
	clusters := api.Group("/clusters")
	clusters.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	clusters.GET("", d.clusterHandler.List)
	clusters.GET("/:id", d.clusterHandler.Detail)
	clusters.POST("", d.clusterHandler.Create)
	clusters.PUT("/:id", d.clusterHandler.Update)
	clusters.DELETE("/:id", d.clusterHandler.Delete)
	clusters.PUT("/:id/status", d.clusterHandler.SetStatus)
	clusters.GET("/:id/status", d.clusterHandler.Status)
	clusters.GET("/:id/namespaces", d.clusterHandler.Namespaces)
	clusters.GET("/:id/component-statuses", d.clusterHandler.ComponentStatuses)
	clusters.GET("/:id/api-resources", d.k8sDiscoveryHandler.ListAPIResources)

	pods := api.Group("/pods")
	pods.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	pods.GET("", d.podHandler.List)
	pods.GET("/detail", d.podHandler.Detail)
	pods.GET("/diagnose", d.podHandler.Diagnose)
	pods.GET("/events", d.podHandler.Events)
	pods.GET("/logs", d.podHandler.Logs)
	pods.GET("/logs/download", d.podHandler.LogsDownload)
	pods.GET("/logs/stream", d.podHandler.LogsStream)
	pods.GET("/files", d.podHandler.ListFiles)
	pods.GET("/file", d.podHandler.ReadFile)
	pods.GET("/file/download", d.podHandler.DownloadFile)
	pods.POST("/file/upload", d.podHandler.UploadFile)
	pods.POST("/file/delete", d.podHandler.DeleteFile)
	pods.POST("/exec", d.podHandler.Exec)
	// Interactive exec via WebSocket (browser can't set Authorization header)
	podsWS := api.Group("/pods")
	podsWS.Use(d.wsAuthMiddleware, d.authorize, d.k8sScopeAuthorize)
	podsWS.GET("/exec/ws", d.podHandler.ExecWS)
	pods.POST("/restart", d.podHandler.Restart)
	pods.POST("/create/yaml", d.podHandler.CreateByYAML)
	pods.POST("/create/simple", d.podHandler.CreateSimple)
	pods.POST("/update/simple", d.podHandler.UpdateSimple)
	pods.DELETE("", d.podHandler.Delete)

	namespaces := api.Group("/namespaces")
	namespaces.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	namespaces.GET("", d.namespaceHandler.List)
	namespaces.GET("/detail", d.namespaceHandler.Detail)
	namespaces.POST("/apply", d.namespaceHandler.Apply)
	namespaces.DELETE("", d.namespaceHandler.Delete)

	nodes := api.Group("/nodes")
	nodes.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	nodes.GET("", d.nodeHandler.List)
	nodes.GET("/detail", d.nodeHandler.Detail)
	nodes.POST("/schedulability", d.nodeHandler.SetSchedulability)
	nodes.PUT("/taints", d.nodeHandler.ReplaceTaints)

	// Workloads
	deployments := api.Group("/deployments")
	deployments.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	deployments.GET("", d.workloadHandler.ListDeployments)
	deployments.GET("/detail", d.workloadHandler.DeploymentDetail)
	deployments.GET("/rollout-status", d.workloadHandler.DeploymentRolloutStatus)
	deployments.POST("/apply", d.workloadHandler.Apply)
	deployments.POST("/scale", d.workloadHandler.DeploymentScale)
	deployments.POST("/container-resources", d.workloadHandler.DeploymentPatchContainerResources)
	deployments.POST("/restart", d.workloadHandler.DeploymentRestart)
	deployments.DELETE("", d.workloadHandler.DeleteDeployment)

	statefulsets := api.Group("/statefulsets")
	statefulsets.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	statefulsets.GET("", d.workloadHandler.ListStatefulSets)
	statefulsets.GET("/detail", d.workloadHandler.StatefulSetDetail)
	statefulsets.POST("/apply", d.workloadHandler.Apply)
	statefulsets.POST("/scale", d.workloadHandler.StatefulSetScale)
	statefulsets.POST("/container-resources", d.workloadHandler.StatefulSetPatchContainerResources)
	statefulsets.POST("/restart", d.workloadHandler.StatefulSetRestart)
	statefulsets.DELETE("", d.workloadHandler.DeleteStatefulSet)

	daemonsets := api.Group("/daemonsets")
	daemonsets.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	daemonsets.GET("", d.workloadHandler.ListDaemonSets)
	daemonsets.GET("/detail", d.workloadHandler.DaemonSetDetail)
	daemonsets.POST("/apply", d.workloadHandler.Apply)
	daemonsets.POST("/container-resources", d.workloadHandler.DaemonSetPatchContainerResources)
	daemonsets.POST("/restart", d.workloadHandler.DaemonSetRestart)
	daemonsets.DELETE("", d.workloadHandler.DeleteDaemonSet)

	cronjobs := api.Group("/cronjobs")
	cronjobs.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	cronjobs.GET("", d.workloadHandler.ListCronJobs)
	cronjobs.GET("/v2", d.workloadHandler.ListCronJobsV2)
	cronjobs.GET("/detail", d.workloadHandler.CronJobDetail)
	cronjobs.GET("/pods", d.workloadHandler.CronJobPods)
	cronjobs.POST("/apply", d.workloadHandler.Apply)
	cronjobs.POST("/container-resources", d.workloadHandler.CronJobPatchContainerResources)
	cronjobs.POST("/suspend", d.workloadHandler.CronJobSuspend)
	cronjobs.POST("/trigger", d.workloadHandler.CronJobTrigger)
	cronjobs.DELETE("", d.workloadHandler.DeleteCronJob)

	jobs := api.Group("/jobs")
	jobs.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	jobs.GET("", d.workloadHandler.ListJobs)
	jobs.GET("/detail", d.workloadHandler.JobDetail)
	jobs.GET("/pods", d.workloadHandler.JobPods)
	jobs.POST("/rerun", d.workloadHandler.JobRerun)
	jobs.POST("/container-resources", d.workloadHandler.JobPatchContainerResources)
	jobs.POST("/apply", d.workloadHandler.Apply)
	jobs.DELETE("", d.workloadHandler.DeleteJob)

	// related pods
	deployments.GET("/pods", d.workloadHandler.DeploymentPods)
	statefulsets.GET("/pods", d.workloadHandler.StatefulSetPods)
	daemonsets.GET("/pods", d.workloadHandler.DaemonSetPods)

	configmaps := api.Group("/configmaps")
	configmaps.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	configmaps.GET("", d.configHandler.ListConfigMaps)
	configmaps.GET("/detail", d.configHandler.ConfigMapDetail)
	configmaps.POST("/apply", d.configHandler.Apply)
	configmaps.DELETE("", d.configHandler.DeleteConfigMap)

	secrets := api.Group("/secrets")
	secrets.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	secrets.GET("", d.configHandler.ListSecrets)
	secrets.GET("/detail", d.configHandler.SecretDetail)
	secrets.POST("/apply", d.configHandler.Apply)
	secrets.DELETE("", d.configHandler.DeleteSecret)

	persistentvolumes := api.Group("/persistentvolumes")
	persistentvolumes.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	persistentvolumes.GET("", d.storageHandler.ListPVs)
	persistentvolumes.GET("/detail", d.storageHandler.Detail)
	persistentvolumes.POST("/apply", d.storageHandler.Apply)
	persistentvolumes.DELETE("", d.storageHandler.Delete)

	persistentvolumeclaims := api.Group("/persistentvolumeclaims")
	persistentvolumeclaims.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	persistentvolumeclaims.GET("", d.storageHandler.ListPVCs)
	persistentvolumeclaims.GET("/detail", d.storageHandler.Detail)
	persistentvolumeclaims.POST("/apply", d.storageHandler.Apply)
	persistentvolumeclaims.DELETE("", d.storageHandler.Delete)

	storageclasses := api.Group("/storageclasses")
	storageclasses.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	storageclasses.GET("", d.storageHandler.ListStorageClasses)
	storageclasses.GET("/detail", d.storageHandler.Detail)
	storageclasses.POST("/apply", d.storageHandler.Apply)
	storageclasses.DELETE("", d.storageHandler.Delete)

	k8sServices := api.Group("/k8s-services")
	k8sServices.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	k8sServices.GET("", d.serviceResourceHandler.List)
	k8sServices.GET("/detail", d.serviceResourceHandler.Detail)
	k8sServices.POST("/apply", d.serviceResourceHandler.Apply)
	k8sServices.DELETE("", d.serviceResourceHandler.Delete)

	ingresses := api.Group("/ingresses")
	ingresses.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	ingresses.GET("", d.ingressHandler.List)
	ingresses.GET("/detail", d.ingressHandler.Detail)
	ingresses.POST("/apply", d.ingressHandler.Apply)
	ingresses.POST("/nginx/restart", d.ingressHandler.RestartNginxPods)
	ingresses.DELETE("", d.ingressHandler.Delete)
	ingresses.GET("/classes", d.ingressHandler.ListClasses)
	ingresses.GET("/classes/detail", d.ingressHandler.DetailClass)
	ingresses.POST("/classes/apply", d.ingressHandler.ApplyClass)
	ingresses.DELETE("/classes", d.ingressHandler.DeleteClass)

	networkPolicies := api.Group("/network-policies")
	networkPolicies.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	networkPolicies.GET("", d.networkPolicyHandler.List)
	networkPolicies.GET("/detail", d.networkPolicyHandler.Detail)
	networkPolicies.POST("/apply", d.networkPolicyHandler.Apply)
	networkPolicies.DELETE("", d.networkPolicyHandler.Delete)

	horizontalPodAutoscalers := api.Group("/horizontal-pod-autoscalers")
	horizontalPodAutoscalers.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	horizontalPodAutoscalers.GET("", d.k8sHPAHandler.List)
	horizontalPodAutoscalers.GET("/detail", d.k8sHPAHandler.Detail)
	horizontalPodAutoscalers.POST("/apply", d.k8sHPAHandler.Apply)
	horizontalPodAutoscalers.DELETE("", d.k8sHPAHandler.Delete)

	k8sResourceWatch := api.Group("/k8s/resource-watch")
	k8sResourceWatch.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	k8sResourceWatch.GET("/stream", d.k8sResourceWatchHandler.Stream)

	events := api.Group("/events")
	events.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	events.GET("", d.eventHandler.List)

	crds := api.Group("/crds")
	crds.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	crds.GET("", d.crdHandler.List)
	crds.GET("/detail", d.crdHandler.Detail)
	crds.POST("/apply", d.crdHandler.Apply)
	crds.DELETE("", d.crdHandler.Delete)

	crs := api.Group("/crs")
	crs.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	crs.GET("/resources", d.crHandler.ListResources)
	crs.GET("", d.crHandler.List)
	crs.GET("/detail", d.crHandler.Detail)
	crs.POST("/apply", d.crHandler.Apply)
	crs.DELETE("", d.crHandler.Delete)

	rbac := api.Group("/rbac")
	rbac.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	rbac.GET("/roles", d.rbacHandler.ListRoles)
	rbac.GET("/rolebindings", d.rbacHandler.ListRoleBindings)
	rbac.GET("/clusterroles", d.rbacHandler.ListClusterRoles)
	rbac.GET("/clusterrolebindings", d.rbacHandler.ListClusterRoleBindings)
	rbac.GET("/detail", d.rbacHandler.Detail)
	rbac.POST("/apply", d.rbacHandler.Apply)
	rbac.DELETE("", d.rbacHandler.Delete)

	serviceAccounts := api.Group("/serviceaccounts")
	serviceAccounts.Use(d.authMiddleware, d.authorize, d.k8sScopeAuthorize, d.opAudit)
	serviceAccounts.GET("", d.serviceAccountHandler.List)
	serviceAccounts.GET("/detail", d.serviceAccountHandler.Detail)
	serviceAccounts.POST("/apply", d.serviceAccountHandler.Apply)
	serviceAccounts.DELETE("", d.serviceAccountHandler.Delete)

}
