package router

import (
	"yunshu/internal/middleware"

	"github.com/gin-gonic/gin"
)

func registerProjectRoutes(api *gin.RouterGroup, d *routeDeps) {
	projectRoutes := api.Group("/projects")
	projectRoutes.Use(d.authMiddleware, d.authorize, d.opAudit)
	projectRoutes.GET("", d.projectHandler.List)
	projectRoutes.POST("", d.projectHandler.Create)
	projectScoped := projectRoutes.Group("/:id", middleware.RequireProjectMemberAccess(d.projectMemberRepo, d.app.Logger))
	projectScoped.PUT("", d.projectHandler.Update)
	projectScoped.DELETE("", d.projectHandler.Delete)
	projectScoped.GET("/members", d.projectHandler.ListProjectMembers)
	projectScoped.POST("/members", d.projectHandler.AddProjectMember)
	projectScoped.PUT("/members/:memberId", d.projectHandler.UpdateProjectMember)
	projectScoped.DELETE("/members/:memberId", d.projectHandler.RemoveProjectMember)
	projectScoped.GET("/servers", d.projectHandler.ListServers)
	projectScoped.POST("/servers", d.projectHandler.UpsertServer)
	projectScoped.GET("/servers/:serverId", d.projectHandler.ServerDetail)
	projectScoped.DELETE("/servers/:serverId", d.projectHandler.DeleteServer)
	projectScoped.POST("/servers/:serverId/exec", d.projectHandler.ExecServerCommand)
	projectScoped.GET("/server-groups/tree", d.projectHandler.ListServerGroups)
	projectScoped.POST("/server-groups", d.projectHandler.UpsertServerGroup)
	projectScoped.PUT("/server-groups/:groupId", d.projectHandler.UpdateServerGroup)
	projectScoped.DELETE("/server-groups/:groupId", d.projectHandler.DeleteServerGroup)
	projectScoped.GET("/cloud-accounts", d.projectHandler.ListCloudAccounts)
	projectScoped.POST("/cloud-accounts", d.projectHandler.UpsertCloudAccount)
	projectScoped.PUT("/cloud-accounts/:accountId", d.projectHandler.UpdateCloudAccount)
	projectScoped.DELETE("/cloud-accounts/:accountId", d.projectHandler.DeleteCloudAccount)
	projectScoped.PUT("/cloud-accounts/:accountId/sync", d.projectHandler.SyncCloudAccount)
	projectScoped.POST("/servers/import", d.projectHandler.ImportServers)
	projectScoped.GET("/servers/import-template", d.projectHandler.ServersImportTemplate)
	projectScoped.GET("/servers/export", d.projectHandler.ExportServers)
	projectScoped.POST("/servers/test", d.projectHandler.TestServer)
	projectScoped.POST("/servers/test/batch", d.projectHandler.BatchTestServers)
	projectScoped.POST("/servers/:serverId/cloud-actions", d.projectHandler.CloudServerAction)
	projectScoped.POST("/servers/sync", d.projectHandler.SyncServers)
	projectScoped.GET("/services", d.projectHandler.ListServices)
	projectScoped.POST("/services", d.projectHandler.UpsertService)
	projectScoped.DELETE("/services/:serviceId", d.projectHandler.DeleteService)
	projectScoped.GET("/log-sources", d.projectHandler.ListLogSources)
	projectScoped.POST("/log-sources", d.projectHandler.UpsertLogSource)
	projectScoped.DELETE("/log-sources/:logSourceId", d.projectHandler.DeleteLogSource)
	projectScoped.GET("/agents/list", d.logAgentHandler.List)
	projectScoped.DELETE("/agents/:agentId", d.logAgentHandler.Delete)
	projectScoped.POST("/agents/heartbeat-refresh", d.logAgentHandler.BatchRefreshHeartbeat)
	projectScoped.GET("/agents/status", d.logAgentHandler.Status)
	projectScoped.POST("/agents/bootstrap", d.logAgentHandler.Bootstrap)
	projectScoped.POST("/agents/rotate-token", d.logAgentHandler.RotateToken)
	projectScoped.GET("/agents/discovery", d.agentDiscoveryHandler.List)
	projectScoped.GET("/logs/stream", d.projectHandler.StreamLogs)
	projectScoped.GET("/logs/export", d.projectHandler.ExportLogs)
	projectScoped.GET("/log-files", d.projectHandler.ListLogFiles)
	projectScoped.GET("/log-units", d.projectHandler.ListLogUnits)

	projectsWS := api.Group("/projects")
	projectsWS.Use(d.wsAuthMiddleware, d.authorize, middleware.RequireProjectMemberAccess(d.projectMemberRepo, d.app.Logger))
	projectsWS.GET("/:id/servers/:serverId/terminal/ws", d.projectHandler.ServerTerminalWS)

	agents := api.Group("/agents")
	agents.Use(d.authMiddleware, d.authorize, d.opAudit)
	agents.POST("/register", d.logAgentHandler.Register)
	api.GET("/agents/runtime-config", d.logAgentHandler.RuntimeConfig)
	api.POST("/agents/public-register", d.logAgentHandler.PublicRegister)
	api.POST("/agents/health/report", d.logAgentHandler.ReportHealth)
	api.POST("/agents/discovery/report", d.agentDiscoveryHandler.Report)

	overview := api.Group("/overview")
	overview.Use(d.authMiddleware, d.authorize, d.opAudit)
	overview.GET("", d.overviewHandler.Get)
	overview.GET("/trends", d.overviewHandler.Trends)
}
