package router

import (
	"yunshu/internal/bootstrap"
	grpcclient "yunshu/internal/grpc/client"
	"yunshu/internal/handler"
	"yunshu/internal/middleware"
	"yunshu/internal/repository"
	"yunshu/internal/service"
)

func Register(app *bootstrap.App, runtimeClient *grpcclient.RuntimeClient) {
	registerSwagger(app)

	systemHandler := handler.NewSystemHandler(app.Config.App.Name, app.Config.App.Env)
	userRepo := repository.NewUserRepository(app.DB)
	departmentRepo := repository.NewDepartmentRepository(app.DB)
	roleRepo := repository.NewRoleRepository(app.DB)
	permissionRepo := repository.NewPermissionRepository(app.DB)

	loginLogRepo := repository.NewLoginLogRepository(app.DB)
	opLogRepo := repository.NewOperationLogRepository(app.DB)
	loginLogSvc := service.NewLoginLogService(loginLogRepo)
	opLogSvc := service.NewOperationLogService(opLogRepo)

	authService := service.NewAuthService(userRepo, app.Redis, app.Config.Auth, app.Mailer, app.Config.App.Name)
	userService := service.NewUserService(userRepo, roleRepo, departmentRepo, app.Enforcer)
	departmentService := service.NewDepartmentService(departmentRepo, userRepo)
	roleService := service.NewRoleService(roleRepo, app.Enforcer)
	permissionService := service.NewPermissionService(permissionRepo, app.Enforcer)
	policyService := service.NewPolicyService(roleRepo, permissionRepo, app.Enforcer)
	k8sScopedPolicyService := service.NewK8sScopedPolicyService(roleRepo, permissionRepo, app.Enforcer)

	regReqRepo := repository.NewRegistrationRequestRepository(app.DB)
	menuRepo := repository.NewMenuRepository(app.DB)
	dictEntryRepo := repository.NewDictEntryRepository(app.DB)
	registrationService := service.NewRegistrationService(regReqRepo, userRepo, app.Redis, app.Config.Auth, app.Mailer, app.Config.App.Name)
	menuService := service.NewMenuService(menuRepo)
	dictEntryService := service.NewDictEntryService(dictEntryRepo)
	alertSilenceSvc := service.NewAlertSilenceService(app.DB)
	projectMemberRepo := repository.NewProjectMemberRepository(app.DB)
	alertAssigneeSvc := service.NewAlertRuleAssigneeService(app.DB, userRepo, projectMemberRepo)
	alertDutySvc := service.NewAlertDutyService(app.DB, userRepo)
	alertService := service.NewAlertService(app.DB, app.Redis, app.Mailer, app.Config.Alert, &service.AlertServiceOptions{
		SilenceSvc:  alertSilenceSvc,
		AssigneeSvc: alertAssigneeSvc,
		DutySvc:     alertDutySvc,
	})
	cloudExpiryRuleSvc := service.NewCloudExpiryRuleService(app.DB)
	alertPolicyService := service.NewAlertPolicyService(app.DB)
	alertDatasourceSvc := service.NewAlertDatasourceService(app.DB)
	alertMonitorRuleSvc := service.NewAlertMonitorRuleService(app.DB)

	clusterRepo := repository.NewK8sClusterRepository(app.DB)
	k8sRuntimeService := service.NewK8sRuntimeService(clusterRepo)
	clusterService := service.NewK8sClusterService(clusterRepo, dictEntryRepo, k8sRuntimeService)
	podService := service.NewK8sPodService(k8sRuntimeService)
	namespaceService := service.NewK8sNamespaceService(k8sRuntimeService)
	nodeService := service.NewK8sNodeService(k8sRuntimeService)
	workloadService := service.NewK8sWorkloadService(k8sRuntimeService)
	configService := service.NewK8sConfigService(k8sRuntimeService)
	storageService := service.NewK8sStorageService(k8sRuntimeService)
	serviceResourceService := service.NewK8sServiceResourceService(k8sRuntimeService)
	ingressService := service.NewK8sIngressService(k8sRuntimeService)
	networkPolicyService := service.NewK8sNetworkPolicyService(k8sRuntimeService)
	eventService := service.NewK8sEventService(k8sRuntimeService)
	crdService := service.NewK8sCRDService(k8sRuntimeService)
	crService := service.NewK8sCRService(k8sRuntimeService)
	rbacService := service.NewK8sRBACService(k8sRuntimeService)
	serviceAccountService := service.NewK8sServiceAccountService(k8sRuntimeService)
	overviewService := service.NewOverviewService(app.DB, k8sRuntimeService, app.Redis)

	projectRepo := repository.NewProjectRepository(app.DB)
	serverRepo := repository.NewServerRepository(app.DB)
	serverGroupRepo := repository.NewServerGroupRepository(app.DB)
	cloudAccountRepo := repository.NewCloudAccountRepository(app.DB)
	serviceRepo := repository.NewServiceRepository(app.DB)
	logRepo := repository.NewLogSourceRepository(app.DB)
	logAgentRepo := repository.NewLogAgentRepository(app.DB)
	agentDiscoveryRepo := repository.NewAgentDiscoveryRepository(app.DB)
	projectMgmtService, err := service.NewProjectMgmtService(projectRepo, serverRepo, serverGroupRepo, cloudAccountRepo, serviceRepo, logRepo, projectMemberRepo, userRepo, app.Config.Security.EncryptionKey)
	if err != nil {
		panic(err)
	}
	logAgentService := service.NewLogAgentService(logAgentRepo, serverRepo, logRepo, app.Config.Agent.RegisterSecret)
	agentDiscoveryService := service.NewAgentDiscoveryService(agentDiscoveryRepo, logAgentRepo, serverRepo)

	authHandler := handler.NewAuthHandler(authService, loginLogSvc)
	loginLogHandler := handler.NewLoginLogHandler(loginLogSvc)
	opLogHandler := handler.NewOperationLogHandler(opLogSvc)
	userHandler := handler.NewUserHandler(userService)
	departmentHandler := handler.NewDepartmentHandler(departmentService)
	roleHandler := handler.NewRoleHandler(roleService)
	permissionHandler := handler.NewPermissionHandler(permissionService)
	policyHandler := handler.NewPolicyHandler(policyService)
	k8sScopedPolicyHandler := handler.NewK8sScopedPolicyHandler(k8sScopedPolicyService)
	regHandler := handler.NewRegistrationHandler(registrationService)
	menuHandler := handler.NewMenuHandler(menuService)
	dictEntryHandler := handler.NewDictEntryHandler(dictEntryService)
	alertHandler := handler.NewAlertHandler(alertService)
	cloudExpiryRuleHandler := handler.NewCloudExpiryRuleHandler(cloudExpiryRuleSvc, alertService)
	alertPolicyHandler := handler.NewAlertPolicyHandler(alertPolicyService)
	alertPlatformHandler := handler.NewAlertPlatformHandler(alertDatasourceSvc, alertSilenceSvc, alertMonitorRuleSvc, alertAssigneeSvc, alertDutySvc)
	adminHandler := handler.NewAdminHandler(app.Redis)
	clusterHandler := handler.NewClusterHandler(clusterService)
	podHandler := handler.NewPodHandler(podService)
	namespaceHandler := handler.NewNamespaceHandler(namespaceService)
	nodeHandler := handler.NewNodeHandler(nodeService)
	workloadHandler := handler.NewWorkloadHandler(workloadService)
	configHandler := handler.NewConfigHandler(configService)
	storageHandler := handler.NewStorageHandler(storageService)
	serviceResourceHandler := handler.NewServiceResourceHandler(serviceResourceService)
	ingressHandler := handler.NewIngressHandler(ingressService)
	networkPolicyHandler := handler.NewNetworkPolicyHandler(networkPolicyService)
	eventHandler := handler.NewEventHandler(eventService)
	crdHandler := handler.NewCRDHandler(crdService)
	crHandler := handler.NewCRHandler(crService)
	rbacHandler := handler.NewRBACHandler(rbacService)
	serviceAccountHandler := handler.NewServiceAccountHandler(serviceAccountService)
	overviewHandler := handler.NewOverviewHandler(overviewService)
	projectHandler := handler.NewProjectHandler(projectMgmtService, runtimeClient.ProjectSrv, runtimeClient.LogSourceSrv)
	logAgentHandler := handler.NewLogAgentHandler(logAgentService, runtimeClient.AgentSrv)
	agentDiscoveryHandler := handler.NewAgentDiscoveryHandler(agentDiscoveryService, runtimeClient.AgentSrv)

	authMiddleware := middleware.Auth(app.Config.Auth.JWTSecret, app.Redis, userRepo, app.Logger)
	wsAuthMiddleware := middleware.WSAuth(app.Config.Auth.JWTSecret, app.Redis, userRepo, app.Logger)
	authorize := middleware.Authorize(app.Enforcer, app.Logger)
	k8sScopeAuthorize := middleware.K8sScopeAuthorize(app.Enforcer, app.Logger, permissionRepo)
	opAudit := middleware.OperationAudit(opLogSvc, app.Logger)

	api := app.Engine.Group("/api/v1")
	// 系统健康检查接口
	api.GET("/health", systemHandler.Health)
	// 认证组
	authGroup := api.Group("/auth")
	// 发送邮箱验证码接口
	authGroup.POST("/verification-code", authHandler.SendEmailCode)
	// 发送登录验证码接口
	authGroup.POST("/login-code", authHandler.SendLoginCodeByUsername)
	// 发送密码登录验证码接口
	authGroup.POST("/password-login-code", authHandler.SendPasswordLoginCode)
	// 登录接口
	authGroup.POST("/login", authHandler.Login)
	// 邮箱登录接口
	authGroup.POST("/email-login", authHandler.EmailLogin)
	// 注册接口（改为申请模式）
	authGroup.POST("/register", middleware.RegistrationRateLimit(app.Redis), regHandler.Apply)

	authAuthed := authGroup.Group("")
	authAuthed.Use(authMiddleware, opAudit)
	authAuthed.POST("/logout", authHandler.Logout)
	authAuthed.GET("/me", authHandler.Me)
	authAuthed.PUT("/me", authHandler.UpdateProfile)
	authAuthed.PUT("/password", authHandler.ChangePassword)

	users := api.Group("/users")
	users.Use(authMiddleware, authorize, opAudit)
	users.GET("", userHandler.List)
	users.GET("/export", userHandler.Export)
	users.GET("/import-template", userHandler.ImportTemplate)
	users.POST("/import", userHandler.Import)
	users.POST("", userHandler.Create)
	users.GET("/:id", userHandler.Detail)
	users.PUT("/:id", userHandler.Update)
	users.DELETE("/:id", userHandler.Delete)
	users.PUT("/:id/roles", userHandler.AssignRoles)

	departments := api.Group("/departments")
	departments.Use(authMiddleware, authorize, opAudit)
	departments.GET("/tree", departmentHandler.Tree)
	departments.GET("/:id", departmentHandler.Detail)
	departments.POST("", departmentHandler.Create)
	departments.PUT("/:id", departmentHandler.Update)
	departments.DELETE("/:id", departmentHandler.Delete)

	roles := api.Group("/roles")
	roles.Use(authMiddleware, authorize, opAudit)
	roles.GET("", roleHandler.List)
	roles.POST("", roleHandler.Create)
	roles.GET("/:id", roleHandler.Detail)
	roles.PUT("/:id", roleHandler.Update)
	roles.DELETE("/:id", roleHandler.Delete)

	permissions := api.Group("/permissions")
	permissions.Use(authMiddleware, authorize, opAudit)
	permissions.GET("", permissionHandler.List)
	permissions.POST("", permissionHandler.Create)
	permissions.GET("/:id", permissionHandler.Detail)
	permissions.PUT("/:id", permissionHandler.Update)
	permissions.DELETE("/:id", permissionHandler.Delete)

	policies := api.Group("/policies")
	policies.Use(authMiddleware, authorize, opAudit)
	policies.GET("", policyHandler.List)
	policies.POST("", policyHandler.Grant)
	policies.DELETE("", policyHandler.Revoke)

	k8sPolicies := api.Group("/k8s-policies")
	k8sPolicies.Use(authMiddleware, authorize, opAudit)
	k8sPolicies.GET("/actions", k8sScopedPolicyHandler.Actions)
	k8sPolicies.GET("/paths", k8sScopedPolicyHandler.Paths)
	k8sPolicies.GET("", k8sScopedPolicyHandler.ListByRole)
	k8sPolicies.POST("/grant", k8sScopedPolicyHandler.Grant)

	// 注册审核接口
	registrations := api.Group("/registrations")
	registrations.Use(authMiddleware, authorize, opAudit)
	registrations.GET("", regHandler.List)
	registrations.POST("/:id/review", regHandler.Review)

	// Admin management (list/unban banned IPs) - super-admin only
	admin := api.Group("/security")
	admin.Use(authMiddleware)
	admin.GET("/banned-ips", adminHandler.ListBannedIPs)
	admin.POST("/banned-ips/unban", adminHandler.UnbanIP)

	// 菜单管理接口
	menus := api.Group("/menus")
	menus.Use(authMiddleware, authorize, opAudit)
	menus.GET("/tree", menuHandler.Tree)
	menus.POST("", menuHandler.Create)
	menus.PUT("/status", menuHandler.BatchStatus)
	menus.PUT("/:id", menuHandler.Update)
	menus.DELETE("/:id", menuHandler.Delete)

	dictEntries := api.Group("/dict/entries")
	dictEntries.Use(authMiddleware, authorize, opAudit)
	dictEntries.GET("", dictEntryHandler.List)
	dictEntries.POST("", dictEntryHandler.Create)
	dictEntries.PUT("/:id", dictEntryHandler.Update)
	dictEntries.DELETE("/:id", dictEntryHandler.Delete)

	dictOptions := api.Group("/dict/options")
	dictOptions.Use(authMiddleware, authorize, opAudit)
	dictOptions.GET("/:dictType", dictEntryHandler.Options)

	alertWebhook := api.Group("/alerts")
	alertWebhook.POST("/webhook/alertmanager", alertHandler.ReceiveAlertmanager)

	alerts := api.Group("/alerts")
	alerts.Use(authMiddleware, authorize, opAudit)
	alerts.GET("/channels", alertHandler.ListChannels)
	alerts.POST("/channels", alertHandler.CreateChannel)
	alerts.PUT("/channels/:id", alertHandler.UpdateChannel)
	alerts.DELETE("/channels/:id", alertHandler.DeleteChannel)
	alerts.POST("/channels/:id/test", alertHandler.TestChannel)
	alerts.GET("/events", alertHandler.ListEvents)
	alerts.GET("/history/stats", alertHandler.HistoryStats)
	alerts.GET("/policies", alertPolicyHandler.List)
	alerts.POST("/policies", alertPolicyHandler.Create)
	alerts.PUT("/policies/:id", alertPolicyHandler.Update)
	alerts.DELETE("/policies/:id", alertPolicyHandler.Delete)

	alerts.GET("/datasources", alertPlatformHandler.ListDatasources)
	alerts.POST("/datasources", alertPlatformHandler.CreateDatasource)
	alerts.GET("/datasources/:id/prometheus-alerts", alertPlatformHandler.PromActiveAlerts)
	alerts.POST("/datasources/:id/query", alertPlatformHandler.PromQuery)
	alerts.POST("/datasources/:id/query_range", alertPlatformHandler.PromQueryRange)
	alerts.PUT("/datasources/:id", alertPlatformHandler.UpdateDatasource)
	alerts.DELETE("/datasources/:id", alertPlatformHandler.DeleteDatasource)

	alerts.GET("/silences", alertPlatformHandler.ListSilences)
	alerts.POST("/silences", alertPlatformHandler.CreateSilence)
	alerts.POST("/silences/batch", alertPlatformHandler.CreateSilenceBatch)
	alerts.PUT("/silences/:id", alertPlatformHandler.UpdateSilence)
	alerts.DELETE("/silences/:id", alertPlatformHandler.DeleteSilence)

	alerts.GET("/monitor-rules", alertPlatformHandler.ListMonitorRules)
	alerts.POST("/monitor-rules", alertPlatformHandler.CreateMonitorRule)
	alerts.PUT("/monitor-rules/:id", alertPlatformHandler.UpdateMonitorRule)
	alerts.DELETE("/monitor-rules/:id", alertPlatformHandler.DeleteMonitorRule)
	alerts.GET("/monitor-rules/:id/assignees", alertPlatformHandler.GetMonitorRuleAssignees)
	alerts.PUT("/monitor-rules/:id/assignees", alertPlatformHandler.UpsertMonitorRuleAssignees)
	alerts.GET("/duty-blocks", alertPlatformHandler.ListDutyBlocks)
	alerts.POST("/duty-blocks", alertPlatformHandler.CreateDutyBlock)
	alerts.PUT("/duty-blocks/:id", alertPlatformHandler.UpdateDutyBlock)
	alerts.DELETE("/duty-blocks/:id", alertPlatformHandler.DeleteDutyBlock)

	// 云服务器到期规则（Cloud Expiry Rules）
	alerts.GET("/cloud-expiry-rules", cloudExpiryRuleHandler.List)
	alerts.POST("/cloud-expiry-rules", cloudExpiryRuleHandler.Create)
	alerts.PUT("/cloud-expiry-rules/:id", cloudExpiryRuleHandler.Update)
	alerts.DELETE("/cloud-expiry-rules/:id", cloudExpiryRuleHandler.Delete)
	alerts.POST("/cloud-expiry-rules/evaluate-now", cloudExpiryRuleHandler.EvaluateNow)

	loginLogs := api.Group("/login-logs")
	loginLogs.Use(authMiddleware, authorize, opAudit)
	loginLogs.GET("/export", loginLogHandler.Export)
	loginLogs.GET("", loginLogHandler.List)
	loginLogs.POST("/delete", loginLogHandler.BatchDelete)
	loginLogs.DELETE("/:id", loginLogHandler.Delete)

	operationLogs := api.Group("/operation-logs")
	operationLogs.Use(authMiddleware, authorize, opAudit)
	operationLogs.GET("/export", opLogHandler.Export)
	operationLogs.GET("", opLogHandler.List)
	operationLogs.POST("/delete", opLogHandler.BatchDelete)
	operationLogs.DELETE("/:id", opLogHandler.Delete)

	// Kubernetes cluster management (Kom SDK)
	clusters := api.Group("/clusters")
	clusters.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	clusters.GET("", clusterHandler.List)
	clusters.GET("/:id", clusterHandler.Detail)
	clusters.POST("", clusterHandler.Create)
	clusters.PUT("/:id", clusterHandler.Update)
	clusters.DELETE("/:id", clusterHandler.Delete)
	clusters.PUT("/:id/status", clusterHandler.SetStatus)
	clusters.GET("/:id/status", clusterHandler.Status)
	clusters.GET("/:id/namespaces", clusterHandler.Namespaces)
	clusters.GET("/:id/component-statuses", clusterHandler.ComponentStatuses)

	pods := api.Group("/pods")
	pods.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	pods.GET("", podHandler.List)
	pods.GET("/detail", podHandler.Detail)
	pods.GET("/events", podHandler.Events)
	pods.GET("/logs", podHandler.Logs)
	pods.GET("/logs/download", podHandler.LogsDownload)
	pods.GET("/logs/stream", podHandler.LogsStream)
	pods.GET("/files", podHandler.ListFiles)
	pods.GET("/file", podHandler.ReadFile)
	pods.GET("/file/download", podHandler.DownloadFile)
	pods.POST("/file/upload", podHandler.UploadFile)
	pods.POST("/file/delete", podHandler.DeleteFile)
	pods.POST("/exec", podHandler.Exec)
	// Interactive exec via WebSocket (browser can't set Authorization header)
	podsWS := api.Group("/pods")
	podsWS.Use(wsAuthMiddleware, authorize)
	podsWS.GET("/exec/ws", podHandler.ExecWS)
	pods.POST("/restart", podHandler.Restart)
	pods.POST("/create/yaml", podHandler.CreateByYAML)
	pods.POST("/create/simple", podHandler.CreateSimple)
	pods.POST("/update/simple", podHandler.UpdateSimple)
	pods.DELETE("", podHandler.Delete)

	namespaces := api.Group("/namespaces")
	namespaces.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	namespaces.GET("", namespaceHandler.List)
	namespaces.GET("/detail", namespaceHandler.Detail)
	namespaces.POST("/apply", namespaceHandler.Apply)
	namespaces.DELETE("", namespaceHandler.Delete)

	nodes := api.Group("/nodes")
	nodes.Use(authMiddleware, authorize, opAudit)
	nodes.GET("", nodeHandler.List)
	nodes.GET("/detail", nodeHandler.Detail)
	nodes.POST("/schedulability", nodeHandler.SetSchedulability)
	nodes.PUT("/taints", nodeHandler.ReplaceTaints)

	// Workloads
	deployments := api.Group("/deployments")
	deployments.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	deployments.GET("", workloadHandler.ListDeployments)
	deployments.GET("/detail", workloadHandler.DeploymentDetail)
	deployments.POST("/apply", workloadHandler.Apply)
	deployments.POST("/scale", workloadHandler.DeploymentScale)
	deployments.POST("/restart", workloadHandler.DeploymentRestart)
	deployments.DELETE("", workloadHandler.DeleteDeployment)

	statefulsets := api.Group("/statefulsets")
	statefulsets.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	statefulsets.GET("", workloadHandler.ListStatefulSets)
	statefulsets.GET("/detail", workloadHandler.StatefulSetDetail)
	statefulsets.POST("/apply", workloadHandler.Apply)
	statefulsets.POST("/scale", workloadHandler.StatefulSetScale)
	statefulsets.POST("/restart", workloadHandler.StatefulSetRestart)
	statefulsets.DELETE("", workloadHandler.DeleteStatefulSet)

	daemonsets := api.Group("/daemonsets")
	daemonsets.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	daemonsets.GET("", workloadHandler.ListDaemonSets)
	daemonsets.GET("/detail", workloadHandler.DaemonSetDetail)
	daemonsets.POST("/apply", workloadHandler.Apply)
	daemonsets.POST("/restart", workloadHandler.DaemonSetRestart)
	daemonsets.DELETE("", workloadHandler.DeleteDaemonSet)

	cronjobs := api.Group("/cronjobs")
	cronjobs.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	cronjobs.GET("", workloadHandler.ListCronJobs)
	cronjobs.GET("/v2", workloadHandler.ListCronJobsV2)
	cronjobs.GET("/detail", workloadHandler.CronJobDetail)
	cronjobs.GET("/pods", workloadHandler.CronJobPods)
	cronjobs.POST("/apply", workloadHandler.Apply)
	cronjobs.POST("/suspend", workloadHandler.CronJobSuspend)
	cronjobs.POST("/trigger", workloadHandler.CronJobTrigger)
	cronjobs.DELETE("", workloadHandler.DeleteCronJob)

	jobs := api.Group("/jobs")
	jobs.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	jobs.GET("", workloadHandler.ListJobs)
	jobs.GET("/detail", workloadHandler.JobDetail)
	jobs.GET("/pods", workloadHandler.JobPods)
	jobs.POST("/rerun", workloadHandler.JobRerun)
	jobs.POST("/apply", workloadHandler.Apply)
	jobs.DELETE("", workloadHandler.DeleteJob)

	// related pods
	deployments.GET("/pods", workloadHandler.DeploymentPods)
	statefulsets.GET("/pods", workloadHandler.StatefulSetPods)
	daemonsets.GET("/pods", workloadHandler.DaemonSetPods)

	configmaps := api.Group("/configmaps")
	configmaps.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	configmaps.GET("", configHandler.ListConfigMaps)
	configmaps.GET("/detail", configHandler.ConfigMapDetail)
	configmaps.POST("/apply", configHandler.Apply)
	configmaps.DELETE("", configHandler.DeleteConfigMap)

	secrets := api.Group("/secrets")
	secrets.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	secrets.GET("", configHandler.ListSecrets)
	secrets.GET("/detail", configHandler.SecretDetail)
	secrets.POST("/apply", configHandler.Apply)
	secrets.DELETE("", configHandler.DeleteSecret)

	persistentvolumes := api.Group("/persistentvolumes")
	persistentvolumes.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	persistentvolumes.GET("", storageHandler.ListPVs)
	persistentvolumes.GET("/detail", storageHandler.Detail)
	persistentvolumes.POST("/apply", storageHandler.Apply)
	persistentvolumes.DELETE("", storageHandler.Delete)

	persistentvolumeclaims := api.Group("/persistentvolumeclaims")
	persistentvolumeclaims.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	persistentvolumeclaims.GET("", storageHandler.ListPVCs)
	persistentvolumeclaims.GET("/detail", storageHandler.Detail)
	persistentvolumeclaims.POST("/apply", storageHandler.Apply)
	persistentvolumeclaims.DELETE("", storageHandler.Delete)

	storageclasses := api.Group("/storageclasses")
	storageclasses.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	storageclasses.GET("", storageHandler.ListStorageClasses)
	storageclasses.GET("/detail", storageHandler.Detail)
	storageclasses.POST("/apply", storageHandler.Apply)
	storageclasses.DELETE("", storageHandler.Delete)

	k8sServices := api.Group("/k8s-services")
	k8sServices.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	k8sServices.GET("", serviceResourceHandler.List)
	k8sServices.GET("/detail", serviceResourceHandler.Detail)
	k8sServices.POST("/apply", serviceResourceHandler.Apply)
	k8sServices.DELETE("", serviceResourceHandler.Delete)

	ingresses := api.Group("/ingresses")
	ingresses.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	ingresses.GET("", ingressHandler.List)
	ingresses.GET("/detail", ingressHandler.Detail)
	ingresses.POST("/apply", ingressHandler.Apply)
	ingresses.POST("/nginx/restart", ingressHandler.RestartNginxPods)
	ingresses.DELETE("", ingressHandler.Delete)
	ingresses.GET("/classes", ingressHandler.ListClasses)
	ingresses.GET("/classes/detail", ingressHandler.DetailClass)
	ingresses.POST("/classes/apply", ingressHandler.ApplyClass)
	ingresses.DELETE("/classes", ingressHandler.DeleteClass)

	networkPolicies := api.Group("/network-policies")
	networkPolicies.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	networkPolicies.GET("", networkPolicyHandler.List)
	networkPolicies.GET("/detail", networkPolicyHandler.Detail)
	networkPolicies.POST("/apply", networkPolicyHandler.Apply)
	networkPolicies.DELETE("", networkPolicyHandler.Delete)

	events := api.Group("/events")
	events.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	events.GET("", eventHandler.List)

	crds := api.Group("/crds")
	crds.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	crds.GET("", crdHandler.List)
	crds.GET("/detail", crdHandler.Detail)
	crds.POST("/apply", crdHandler.Apply)
	crds.DELETE("", crdHandler.Delete)

	crs := api.Group("/crs")
	crs.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	crs.GET("/resources", crHandler.ListResources)
	crs.GET("", crHandler.List)
	crs.GET("/detail", crHandler.Detail)
	crs.POST("/apply", crHandler.Apply)
	crs.DELETE("", crHandler.Delete)

	rbac := api.Group("/rbac")
	rbac.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	rbac.GET("/roles", rbacHandler.ListRoles)
	rbac.GET("/rolebindings", rbacHandler.ListRoleBindings)
	rbac.GET("/clusterroles", rbacHandler.ListClusterRoles)
	rbac.GET("/clusterrolebindings", rbacHandler.ListClusterRoleBindings)
	rbac.GET("/detail", rbacHandler.Detail)
	rbac.POST("/apply", rbacHandler.Apply)
	rbac.DELETE("", rbacHandler.Delete)

	serviceAccounts := api.Group("/serviceaccounts")
	serviceAccounts.Use(authMiddleware, authorize, k8sScopeAuthorize, opAudit)
	serviceAccounts.GET("", serviceAccountHandler.List)
	serviceAccounts.GET("/detail", serviceAccountHandler.Detail)
	serviceAccounts.POST("/apply", serviceAccountHandler.Apply)
	serviceAccounts.DELETE("", serviceAccountHandler.Delete)

	projects := api.Group("/projects")
	projects.Use(authMiddleware, authorize, opAudit)
	projects.GET("", projectHandler.List)
	projects.POST("", projectHandler.Create)
	projects.PUT("/:id", projectHandler.Update)
	projects.DELETE("/:id", projectHandler.Delete)
	projects.GET("/:id/members", projectHandler.ListProjectMembers)
	projects.POST("/:id/members", projectHandler.AddProjectMember)
	projects.PUT("/:id/members/:memberId", projectHandler.UpdateProjectMember)
	projects.DELETE("/:id/members/:memberId", projectHandler.RemoveProjectMember)
	projects.GET("/:id/servers", projectHandler.ListServers)
	projects.POST("/:id/servers", projectHandler.UpsertServer)
	projects.GET("/:id/servers/:serverId", projectHandler.ServerDetail)
	projects.DELETE("/:id/servers/:serverId", projectHandler.DeleteServer)
	projects.POST("/:id/servers/:serverId/exec", projectHandler.ExecServerCommand)
	projects.GET("/:id/server-groups/tree", projectHandler.ListServerGroups)
	projects.POST("/:id/server-groups", projectHandler.UpsertServerGroup)
	projects.PUT("/:id/server-groups/:groupId", projectHandler.UpdateServerGroup)
	projects.DELETE("/:id/server-groups/:groupId", projectHandler.DeleteServerGroup)
	projects.GET("/:id/cloud-accounts", projectHandler.ListCloudAccounts)
	projects.POST("/:id/cloud-accounts", projectHandler.UpsertCloudAccount)
	projects.PUT("/:id/cloud-accounts/:accountId", projectHandler.UpdateCloudAccount)
	projects.DELETE("/:id/cloud-accounts/:accountId", projectHandler.DeleteCloudAccount)
	projects.PUT("/:id/cloud-accounts/:accountId/sync", projectHandler.SyncCloudAccount)
	projects.POST("/:id/servers/import", projectHandler.ImportServers)
	projects.GET("/:id/servers/import-template", projectHandler.ServersImportTemplate)
	projects.GET("/:id/servers/export", projectHandler.ExportServers)
	projects.POST("/:id/servers/test", projectHandler.TestServer)
	projects.POST("/:id/servers/test/batch", projectHandler.BatchTestServers)
	projects.POST("/:id/servers/:serverId/cloud-actions", projectHandler.CloudServerAction)
	projects.POST("/:id/servers/sync", projectHandler.SyncServers)
	projects.GET("/:id/services", projectHandler.ListServices)
	projects.POST("/:id/services", projectHandler.UpsertService)
	projects.DELETE("/:id/services/:serviceId", projectHandler.DeleteService)
	projects.GET("/:id/log-sources", projectHandler.ListLogSources)
	projects.POST("/:id/log-sources", projectHandler.UpsertLogSource)
	projects.DELETE("/:id/log-sources/:logSourceId", projectHandler.DeleteLogSource)
	projects.GET("/:id/agents/list", logAgentHandler.List)
	projects.POST("/:id/agents/heartbeat-refresh", logAgentHandler.BatchRefreshHeartbeat)
	projects.GET("/:id/agents/status", logAgentHandler.Status)
	projects.POST("/:id/agents/bootstrap", logAgentHandler.Bootstrap)
	projects.POST("/:id/agents/rotate-token", logAgentHandler.RotateToken)
	projects.GET("/:id/agents/discovery", agentDiscoveryHandler.List)
	projects.GET("/:id/logs/stream", projectHandler.StreamLogs)
	projects.GET("/:id/logs/export", projectHandler.ExportLogs)
	projects.GET("/:id/log-files", projectHandler.ListLogFiles)
	projects.GET("/:id/log-units", projectHandler.ListLogUnits)

	projectsWS := api.Group("/projects")
	projectsWS.Use(wsAuthMiddleware, authorize)
	projectsWS.GET("/:id/servers/:serverId/terminal/ws", projectHandler.ServerTerminalWS)

	agents := api.Group("/agents")
	agents.Use(authMiddleware, authorize, opAudit)
	agents.POST("/register", logAgentHandler.Register)
	api.GET("/agents/runtime-config", logAgentHandler.RuntimeConfig)
	api.POST("/agents/public-register", logAgentHandler.PublicRegister)
	api.POST("/agents/health/report", logAgentHandler.ReportHealth)
	api.POST("/agents/discovery/report", agentDiscoveryHandler.Report)

	overview := api.Group("/overview")
	overview.Use(authMiddleware, authorize, opAudit)
	overview.GET("", overviewHandler.Get)
	overview.GET("/trends", overviewHandler.Trends)
}
